<?php


use Phinx\Seed\AbstractSeed;

class ClubsSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
    	$data = [

[
	'idclub' => '1',
	'cdstatus' => 'N',
	'nmsearch' => 'ABC',
	'nmclub' => 'ABC',
	'nmfull' => 'A.B.C.',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark',
	'ftaddress' => 'Boelelaan 50',
	'ftpostalcode' => '1082LR',
	'nmcity' => 'AMSTERDAM',
	'ftphone' => '020-6445575',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '2',
	'cdstatus' => 'N',
	'nmsearch' => 'ADO',
	'nmclub' => 'ADO',
	'nmfull' => 'DATA CIRCUIT A.D.O.',
	'ftlocation' => 'Den Haag',
	'ftfield' => 'Gem.Honkbalstadion\'Escamp III\'',
	'ftaddress' => 'Erasmusweg/Dedemsvaartweg',
	'nmcity' => 'DEN HAAG',
	'ftphone' => '070-3669722',
	'is_featured' => '1',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '3',
	'cdstatus' => 'N',
	'nmsearch' => 'ALCMA',
	'nmclub' => 'Alcm Victrix',
	'nmfull' => 'v.a.v.v. ALCMARIA VICTRIX',
	'ftlocation' => 'Alkmaar',
	'ftfield' => '\'Egmonderhout\'',
	'ftaddress' => 'Terborchlaan',
	'nmcity' => 'ALKMAAR',
	'ftphone' => '072-5113934',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '4',
	'cdstatus' => 'N',
	'nmsearch' => 'ALLIN',
	'nmclub' => 'All In',
	'nmfull' => 'v.h.s.v. ALL INN',
	'ftlocation' => 'Veldhoven',
	'ftfield' => 'Sportpark \'De Heikant\'',
	'ftaddress' => 'Heikantsebaan',
	'ftpostalcode' => '5508LL',
	'nmcity' => 'VELDHOVEN',
	'ftphone' => '040-2542370',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '5',
	'cdstatus' => 'N',
	'nmsearch' => 'BAN',
	'nmclub' => 'BAN TOPA',
	'nmfull' => 'o.s.c. BAN TOPA',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark de Toekomst',
	'ftaddress' => 'Burg.Stramanweg 1101',
	'nmcity' => 'OUDERKERK A/D AMSTEL',
	'ftphone' => '020-6003448',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '6',
	'cdstatus' => 'N',
	'nmsearch' => 'ALPH',
	'nmclub' => 'Alphians',
	'nmfull' => 'b.s.c. ALPHIANS',
	'ftlocation' => 'Alphen aan den Rijn',
	'ftfield' => 'Sportpark \'De Bijlen\'',
	'ftaddress' => 'Sportlaan 7',
	'ftpostalcode' => '2406LD',
	'nmcity' => 'ALPHEN A/D RIJN',
	'ftphone' => '0172-473116',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '7',
	'cdstatus' => 'N',
	'nmsearch' => 'AMSTE',
	'nmclub' => 'Amstelland',
	'nmfull' => 'h.s.c. AMSTELLAND',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark \'Strandvliet\'',
	'ftaddress' => 'Zwarte Laantje 5',
	'nmcity' => 'DUIVENDRECHT',
	'ftphone' => '020-6965551',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '8',
	'cdstatus' => 'N',
	'nmsearch' => 'BEAGL',
	'nmclub' => 'Beagles',
	'nmfull' => 'h.s.v. THE BEAGLES',
	'ftlocation' => 'Bovenkarspel',
	'ftfield' => 'Sportcomplex \'De Rozenboom\'',
	'nmcity' => 'BOVENKARSPEL',
	'ftphone' => '0228-515641',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '9',
	'cdstatus' => 'N',
	'nmsearch' => 'BEARS',
	'nmclub' => 'Bears',
	'nmfull' => 'THE BEARS',
	'ftlocation' => 'Bergen',
	'ftfield' => '\'De Kiefthoek\'',
	'ftpostalcode' => '1861PH',
	'nmcity' => 'BERGEN',
	'ftphone' => '072-5895778',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '10',
	'cdstatus' => 'N',
	'nmsearch' => 'DIO',
	'nmclub' => 'DIO',
	'nmfull' => 'D.I.O.',
	'ftlocation' => 'Haarlem',
	'ftaddress' => 'BelgiÃƒÂ«laan (Europawijk)',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5358824',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '11',
	'cdstatus' => 'N',
	'nmsearch' => 'BIRDS',
	'nmclub' => 'Birds',
	'nmfull' => 'z.b.s.v. BIRDS',
	'ftlocation' => 'Zoetermeer',
	'ftfield' => 'Burg. Van Tuyl Sportpark',
	'ftaddress' => 'Van der Hagenstraat',
	'ftpostalcode' => '2722NT',
	'nmcity' => 'ZOETERMEER',
	'ftphone' => '079-3413020',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '12',
	'cdstatus' => 'N',
	'nmsearch' => 'BLSOX',
	'nmclub' => 'Blue Sox',
	'nmfull' => 'h.s.v. BLUE SOX',
	'ftlocation' => 'Bladel',
	'ftfield' => 'Zwembadcomplex De Smagtenbocht',
	'ftaddress' => 'Bossingel 1',
	'ftpostalcode' => '5531NH',
	'nmcity' => 'BLADEL',
	'ftphone' => '0497-381853',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '13',
	'cdstatus' => 'N',
	'nmsearch' => 'BLOEM',
	'nmclub' => 'Bloemendaal',
	'nmfull' => 'b.v.c. BLOEMENDAAL',
	'ftlocation' => 'Bloemendaal',
	'ftaddress' => 'Bergweg',
	'nmcity' => 'BLOEMENDAAL',
	'ftphone' => '023-5375300',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '14',
	'cdstatus' => 'N',
	'nmsearch' => 'BLOKE',
	'nmclub' => 'Blokes',
	'nmfull' => 'THE BLOKES',
	'ftlocation' => 'Veendam',
	'ftfield' => 'Sportpark \'De Langeleegte\'',
	'ftaddress' => 'Ontspanningslaan 1',
	'nmcity' => 'VEENDAM',
	'ftphone' => '0598-626070',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '15',
	'cdstatus' => 'N',
	'nmsearch' => 'BLBIR',
	'nmclub' => 'Blue Birds',
	'nmfull' => 'BLUE BIRDS',
	'ftlocation' => 'Delft',
	'ftfield' => 'Sportpark \'Kruithuisweg\'',
	'ftaddress' => 'Mekelweg',
	'nmcity' => 'DELFT',
	'ftphone' => '015-2563322',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '16',
	'cdstatus' => 'N',
	'nmsearch' => 'BLDEV',
	'nmclub' => 'Blue Devils',
	'nmfull' => 's.v. BLUE DEVILS',
	'ftlocation' => 'Meppel',
	'ftfield' => 'Sportpark Koedijkslanden',
	'nmcity' => 'MEPPEL',
	'ftphone' => '0522-260913',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '17',
	'cdstatus' => 'N',
	'nmsearch' => 'BLSOC',
	'nmclub' => 'Blue Socks',
	'nmfull' => 'v.h.c. BLUE SOCKS',
	'ftlocation' => 'Veenendaal',
	'ftfield' => 'Sportpark \'Spitsbergen\'',
	'ftaddress' => 'Grote Beer 50',
	'ftpostalcode' => '3902HJ',
	'nmcity' => 'VEENENDAAL',
	'ftphone' => '0318-515929',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '18',
	'cdstatus' => 'N',
	'nmsearch' => 'SPIJK',
	'nmclub' => 'Spijkenisse',
	'nmfull' => 'h.s.v. SPIJKENISSE',
	'ftlocation' => 'Spijkenisse',
	'ftfield' => 'Sportpark \'De Brug\'',
	'nmcity' => 'SPIJKENISSE',
	'ftphone' => '0181-618849',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '19',
	'cdstatus' => 'N',
	'nmsearch' => 'BRAVE',
	'nmclub' => 'Braves',
	'nmfull' => 'h.s.v. THE BRAVES',
	'ftlocation' => 'Gouda',
	'ftfield' => 'Sportcomplex \'De Uiterwaard\'',
	'ftaddress' => 'Uiterwaardseweg 5',
	'ftpostalcode' => '2807CD',
	'nmcity' => 'GOUDA',
	'ftphone' => '0182-580606',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '20',
	'cdstatus' => 'N',
	'nmsearch' => 'BSM',
	'nmclub' => 'BSM',
	'nmfull' => 'B.S.M.',
	'ftlocation' => 'Bennebroek',
	'ftfield' => 'Sportpark \'\'t Rottegat\'',
	'ftaddress' => 'einde Ing. Sweerslaan',
	'ftpostalcode' => '2121VN',
	'nmcity' => 'BENNEBROEK',
	'ftphone' => '02502-6156',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '21',
	'cdstatus' => 'N',
	'nmsearch' => 'BULLF',
	'nmclub' => 'Bullfighters',
	'nmfull' => 'b.s.v. BULLFIGHTERS',
	'ftlocation' => 'Cuyk',
	'ftfield' => 'Sportp.De Groenendijkse Kampen',
	'nmcity' => 'CUYK',
	'ftphone' => '0485-317630',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '22',
	'cdstatus' => 'N',
	'nmsearch' => 'CARDI',
	'nmclub' => 'Cardinals',
	'nmfull' => 'b.s.c. CARDINALS',
	'ftlocation' => 'Oss',
	'ftfield' => 'Sportpark \'De Rusheuvel\'',
	'ftaddress' => 'Macharenseweg',
	'ftpostalcode' => '5347KA',
	'nmcity' => 'OSS',
	'ftphone' => '0412-625252',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '23',
	'cdstatus' => 'N',
	'nmsearch' => 'CARIB',
	'nmclub' => 'Caribe',
	'nmfull' => 'b.s.c. CARIBE',
	'ftlocation' => 'Groningen',
	'ftfield' => 'Sportpark Corpus den Hoorn',
	'nmcity' => 'GRONINGEN',
	'ftphone' => '050-5250095',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '24',
	'cdstatus' => 'N',
	'nmsearch' => 'CATCH',
	'nmclub' => 'Catch',
	'nmfull' => 'h.s.v. CATCH',
	'ftlocation' => 'Nijverdal',
	'ftfield' => 'Sportpark \'Gagelman\'',
	'nmcity' => 'NIJVERDAL',
	'ftphone' => '0548-611439',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '25',
	'cdstatus' => 'N',
	'nmsearch' => 'CELER',
	'nmclub' => 'Celeritas',
	'nmfull' => 'h.s.v. CELERITAS',
	'ftlocation' => 'Den Haag',
	'ftaddress' => 'Leyweg/hoek Noordweg',
	'nmcity' => 'WATERINGEN',
	'ftphone' => '01742-5151',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '26',
	'cdstatus' => 'N',
	'nmsearch' => 'CRASH',
	'nmclub' => 'Crash Zwolle',
	'nmfull' => 'h.s.v. \'CRASH ZWOLLE\'',
	'ftlocation' => 'Zwolle',
	'ftaddress' => 'Peterskampweg 1',
	'ftpostalcode' => '8031LK',
	'nmcity' => 'ZWOLLE',
	'ftphone' => '038-4545134',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '27',
	'cdstatus' => 'N',
	'nmsearch' => 'CROM',
	'nmclub' => 'Cromtigers',
	'nmfull' => 'b.s.c. CROMTIGERS',
	'ftlocation' => 'Krommenie',
	'ftfield' => 'Sportpark \'De Slibkuil\'',
	'ftaddress' => 'Komarowlaan',
	'ftpostalcode' => '1562TV',
	'nmcity' => 'KROMMENIE',
	'ftphone' => '075-6284780',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '28',
	'cdstatus' => 'N',
	'nmsearch' => 'COUNT',
	'nmclub' => 'County Hitters',
	'nmfull' => 'COUNTY HITTERS',
	'ftlocation' => 'Doetinchem',
	'ftfield' => 'Sportpark \'Bezelhorst\'',
	'ftaddress' => 'Bezelhorstweg 89',
	'ftpostalcode' => '7009KK',
	'nmcity' => 'DOETINCHEM',
	'ftphone' => '0314-330752',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '29',
	'cdstatus' => 'N',
	'nmsearch' => 'DOS',
	'nmclub' => 'Dos \'32',
	'nmfull' => 'c.s.v. D.O.S. \'32',
	'ftlocation' => 'Rotterdam',
	'ftaddress' => 'v.d. Duijn van Maasdamweg 203',
	'nmcity' => 'ROTTERDAM',
	'ftphone' => '010-4225602',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '30',
	'cdstatus' => 'N',
	'nmsearch' => 'DRACH',
	'nmclub' => 'Drachten',
	'nmfull' => 'h.s.v. DRACHTEN',
	'ftlocation' => 'Drachten',
	'ftaddress' => 'Sportlaan 9',
	'ftpostalcode' => '9203NV',
	'nmcity' => 'DRACHTEN',
	'ftphone' => '0512-522433',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '31',
	'cdstatus' => 'N',
	'nmsearch' => 'DSC74',
	'nmclub' => 'DSC \'74',
	'nmfull' => 'D.S.C. \'74',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Sportcomplex Boerhaavelaan',
	'ftaddress' => 'Boerhaavelaan',
	'ftpostalcode' => '2035RX',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5333647',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '32',
	'cdstatus' => 'N',
	'nmsearch' => 'DSSHB',
	'nmclub' => 'DSS',
	'nmfull' => 'r.k.h.v. D.S.S.',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Pim Mulierstadion',
	'ftaddress' => 'Jaap Edenlaan 3',
	'ftpostalcode' => '2024BW',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5272678',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '33',
	'cdstatus' => 'N',
	'nmsearch' => 'DUCKS',
	'nmclub' => 'Ducks',
	'nmfull' => 'j.r.c. DUCKS',
	'ftlocation' => 'Boxtel',
	'ftfield' => 'Sportcomplex \'Den Wielakker\'',
	'ftaddress' => 'Scheidingsweg 3',
	'ftpostalcode' => '5283VJ',
	'nmcity' => 'BOXTEL',
	'ftphone' => '0411-676411',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '34',
	'cdstatus' => 'N',
	'nmsearch' => 'DVH',
	'nmclub' => 'D.V.H.',
	'nmfull' => 'h.s.v. D.V.H.',
	'ftlocation' => 'Amstelveen',
	'ftfield' => 'KLM-Sportcentrum',
	'ftaddress' => 'Wimbledonpark 2',
	'ftpostalcode' => '1185XN',
	'nmcity' => 'AMSTELVEEN',
	'ftphone' => '020-6493800',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '35',
	'cdstatus' => 'N',
	'nmsearch' => 'DVS',
	'nmclub' => 'DVS',
	'nmfull' => 'D.V.S.',
	'ftlocation' => 'Waalre',
	'ftfield' => 'Gem. Sportpark',
	'ftaddress' => 'Mr. Slootweg',
	'nmcity' => 'WAALRE',
	'ftphone' => '040-2215890',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '36',
	'cdstatus' => 'N',
	'nmsearch' => 'EAGLE',
	'nmclub' => 'Eagles',
	'nmfull' => 'h.s.v. THE EAGLES',
	'ftlocation' => 'Deventer',
	'ftaddress' => 'Burgerdijkstraat (Watertoren)',
	'ftpostalcode' => '7413PZ',
	'nmcity' => 'DEVENTER',
	'ftphone' => '0570-628924',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '37',
	'cdstatus' => 'N',
	'nmsearch' => 'EDO',
	'nmclub' => 'EDO',
	'nmfull' => 'h.s.c. E.D.O.',
	'ftlocation' => 'Haarlem',
	'ftaddress' => 'Mr. J. Gerritszlaan',
	'ftpostalcode' => '2024KE',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5255675',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '38',
	'cdstatus' => 'N',
	'nmsearch' => 'EHS',
	'nmclub' => 'EHS',
	'nmfull' => 'E.H.S.',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Van der Aartsportpark',
	'ftaddress' => 'Van der Aartweg',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5373021',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '39',
	'cdstatus' => 'N',
	'nmsearch' => 'EMMEN',
	'nmclub' => 'Emmen',
	'nmfull' => 's.h.v. EMMEN',
	'ftlocation' => 'Emmen',
	'ftfield' => 'Sportpark \'De Meerdijk\'',
	'nmcity' => 'EMMEN',
	'ftphone' => '0591-626089',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '40',
	'cdstatus' => 'N',
	'nmsearch' => 'ESCA',
	'nmclub' => 'ESCA',
	'nmfull' => 'E.S.C.A.',
	'ftlocation' => 'Arnhem',
	'ftfield' => 'Valkenhuizen',
	'ftaddress' => 'Monnikensteeg',
	'nmcity' => 'ARNHEM',
	'ftphone' => '026-3515795',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '41',
	'cdstatus' => 'N',
	'nmsearch' => 'EUROS',
	'nmclub' => 'Euro Stars',
	'nmfull' => 'h.o.p. Service Euro Stars',
	'ftlocation' => 'Capelle aan den IJssel',
	'ftfield' => 'Sportpark \'Schenkel\'',
	'ftaddress' => 'Capelseweg',
	'ftpostalcode' => '2907XA',
	'nmcity' => 'CAPELLE AAN DEN IJSSEL',
	'ftphone' => '010-4518625',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '42',
	'cdstatus' => 'N',
	'nmsearch' => 'FAK',
	'nmclub' => 'FAK',
	'nmfull' => 's.v. F.A.K.',
	'ftlocation' => 'De Bilt',
	'ftfield' => 'Sportpark \'Weltevreden\'',
	'nmcity' => 'DE BILT',
	'ftphone' => '030-2204575',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '43',
	'cdstatus' => 'N',
	'nmsearch' => 'FALCO',
	'nmclub' => 'Falcons',
	'nmfull' => 'b.s.v. FALCONS',
	'ftlocation' => 'Lelystad',
	'ftaddress' => 'Beginweg 2',
	'ftpostalcode' => '8222AJ',
	'nmcity' => 'LELYSTAD',
	'ftphone' => '0320-246263',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '44',
	'cdstatus' => 'N',
	'nmsearch' => 'FENIK',
	'nmclub' => 'Feniks',
	'nmfull' => 'h.s.v. FENIKS',
	'ftlocation' => 'Made',
	'ftfield' => 'Sportpark \'De Schietberg\'',
	'nmcity' => 'MADE',
	'ftphone' => '0162-685727',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '45',
	'cdstatus' => 'N',
	'nmsearch' => 'SPARTA/F',
	'nmclub' => 'SPARTA/F.',
	'nmfull' => 'SPARTA/FEYENOORD',
	'ftlocation' => 'Rotterdam',
	'ftaddress' => 'Edo Bergsmaweg 12',
	'ftpostalcode' => '3077PX',
	'nmcity' => 'ROTTERDAM',
	'ftphone' => '010-4790483',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '46',
	'cdstatus' => 'N',
	'nmsearch' => 'FLAGS',
	'nmclub' => 'Flags',
	'nmfull' => 'b.s.c. THE FLAGS',
	'ftlocation' => 'Lisse',
	'ftfield' => 'Gem. Sportpark \'Ter Specke\'',
	'ftaddress' => 'Spekkelaan',
	'nmcity' => 'LISSE',
	'ftphone' => '0252-418226',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '47',
	'cdstatus' => 'N',
	'nmsearch' => 'FPETR',
	'nmclub' => 'Flying Petrels',
	'nmfull' => 'h.s.v. FLYING PETRELS',
	'ftlocation' => 'Purmerend',
	'ftfield' => 'Sportcomplex \'De Dop\'',
	'ftaddress' => 'Van IJsendijkstraat',
	'nmcity' => 'PURMEREND',
	'ftphone' => '0299-435818',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '48',
	'cdstatus' => 'N',
	'nmsearch' => 'GELDR',
	'nmclub' => 'Geldrop',
	'nmfull' => 'h.s.c. GELDROP',
	'ftlocation' => 'Geldrop',
	'ftfield' => 'Sportpark \'De Bronzenwei\'',
	'ftaddress' => 'Gijzenrooiseweg 3',
	'ftpostalcode' => '5661PA',
	'nmcity' => 'GELDROP',
	'ftphone' => '040-2863521',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '49',
	'cdstatus' => 'N',
	'nmsearch' => 'GOLDE',
	'nmclub' => 'Golden Eagles',
	'nmfull' => 'THE GOLDEN EAGLES',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'TYBB Terrein',
	'ftaddress' => 'Schalkwijkerweg',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5338606',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '50',
	'cdstatus' => 'N',
	'nmsearch' => 'GRCAP',
	'nmclub' => 'Green Caps',
	'nmfull' => 'h.s.v. GREEN CAPS',
	'ftlocation' => 'Emmeloord',
	'ftaddress' => 'Pilotenweg',
	'nmcity' => 'EMMELOORD',
	'ftphone' => '0527-619347',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '51',
	'cdstatus' => 'N',
	'nmsearch' => 'GRSOX',
	'nmclub' => 'Green Sox',
	'nmfull' => 'm.b.s.c. THE GREEN SOX',
	'ftlocation' => 'Middelburg',
	'ftfield' => 'Sportcomplex \'De Kruitmolen\'',
	'ftaddress' => 'Kruitmolenlaan 127',
	'ftpostalcode' => '4377KP',
	'nmcity' => 'MIDDELBURG',
	'ftphone' => '0118-634862',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '52',
	'cdstatus' => 'N',
	'nmsearch' => 'GROEN',
	'nmclub' => 'Groenoord',
	'nmfull' => 's.v. GROENOORD',
	'ftlocation' => 'Vlaardingen',
	'ftfield' => 'Sportcomplex Vlaardingen Holy',
	'ftaddress' => 'Zwaluwenlaan 480',
	'ftpostalcode' => '3136VH',
	'nmcity' => 'VLAARDINGEN',
	'ftphone' => '010-4749196',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '53',
	'cdstatus' => 'N',
	'nmsearch' => 'HAARL',
	'nmclub' => 'Haarlem hfc',
	'nmfull' => 'h.f.c. HAARLEM',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Van der Aartsportpark',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5375732',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '54',
	'cdstatus' => 'N',
	'nmsearch' => 'HAARL',
	'nmclub' => 'Haarlem sc',
	'nmfull' => 's.c. HAARLEM',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Noordersportpark',
	'ftaddress' => 'Melkerijpad',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5264110',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '55',
	'cdstatus' => 'N',
	'nmsearch' => 'NICOL',
	'nmclub' => 'Haarlem Nicols',
	'nmfull' => 's.c. HAARLEM NICOLS',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Pim Mulierstadion',
	'ftaddress' => 'Jaap Edenlaan 3',
	'ftpostalcode' => '2024BW',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5257121',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '56',
	'cdstatus' => 'N',
	'nmsearch' => 'HAWKS',
	'nmclub' => 'Hawks',
	'nmfull' => 'THE HAWKS',
	'ftlocation' => 'Dordrecht',
	'ftfield' => 'Sportcomplex \'Krommedijk\'',
	'nmcity' => 'DORDRECHT',
	'ftphone' => '078-6134573',
	'is_featured' => '1',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '57',
	'cdstatus' => 'N',
	'nmsearch' => 'HAZEN',
	'nmclub' => 'Hazenkamp',
	'nmfull' => 'DE HAZENKAMP',
	'ftlocation' => 'Nijmegen',
	'nmcity' => 'NIJMEGEN',
	'ftphone' => '024-3557484',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '58',
	'cdstatus' => 'N',
	'nmsearch' => 'HBS',
	'nmclub' => 'HBS',
	'nmfull' => 'H.B.S.',
	'ftlocation' => 'Den Bosch',
	'ftaddress' => 'De Saren 8',
	'nmcity' => 'DEN BOSCH',
	'ftphone' => '073-6425609',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '59',
	'cdstatus' => 'A',
	'nmsearch' => 'HCAW',
	'nmclub' => 'HCAW',
	'nmfull' => 'MR.COCKER HCAW',
	'ftlocation' => 'Bussum',
	'ftfield' => 'Sportvallei Zanderijweg',
	'ftaddress' => 'Zanderijweg 4-6',
	'ftpostalcode' => '1403XV',
	'nmcity' => 'BUSSUM',
	'ftphone' => '035-6931430',
	'is_featured' => '1',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '60',
	'cdstatus' => 'N',
	'nmsearch' => 'DOUBL',
	'nmclub' => 'Double Stars',
	'nmfull' => 'b.s.c. DOUBLE STARS HEILOO',
	'ftlocation' => 'Heiloo',
	'ftfield' => 'Sportpark \'Het Vennewater\'',
	'ftpostalcode' => '1852JC',
	'nmcity' => 'HEILOO',
	'ftphone' => '072-5334321',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '61',
	'cdstatus' => 'N',
	'nmsearch' => 'HERON',
	'nmclub' => 'Herons',
	'nmfull' => 'b.c. THE HERONS',
	'ftlocation' => 'Heerhugowaard',
	'ftfield' => 'Sportpark \'De Vork\'',
	'ftpostalcode' => '1704BA',
	'nmcity' => 'HEERHUGOWAARD',
	'ftphone' => '072-5717350',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '62',
	'cdstatus' => 'N',
	'nmsearch' => 'HICKO',
	'nmclub' => 'Hickory',
	'nmfull' => 'b.s.c. HICKORY',
	'ftlocation' => 'Winterswijk',
	'nmcity' => 'WINTERSWIJK',
	'ftphone' => '0543-517764',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '63',
	'cdstatus' => 'N',
	'nmsearch' => 'HILVE',
	'nmclub' => 'Hilversum',
	'nmfull' => 'a.s.c. HILVERSUM',
	'ftlocation' => 'Hilversum',
	'ftfield' => 'Sportpark Loosdrecht',
	'nmcity' => 'HILVERSUM',
	'ftphone' => '035-5826100',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '64',
	'cdstatus' => 'N',
	'nmsearch' => 'HITTE',
	'nmclub' => 'Hittem \'79',
	'nmfull' => 'HITTEM \'79',
	'ftlocation' => 'Haaksbergen',
	'ftfield' => 'Sportpark \'De Greune\'',
	'ftaddress' => 'Kolenbranderwerg 11',
	'ftpostalcode' => '7482SE',
	'nmcity' => 'HAAKSBERGEN',
	'ftphone' => '053-5724106',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '65',
	'cdstatus' => 'N',
	'nmsearch' => 'HMS',
	'nmclub' => 'HMS',
	'nmfull' => 'H.M.S.',
	'ftlocation' => 'Utrecht',
	'ftfield' => 'Sportpark Overvecht-Noord',
	'ftaddress' => 'Manitobadreef',
	'ftpostalcode' => '3572XN',
	'nmcity' => 'UTRECHT',
	'ftphone' => '030-2617087',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '66',
	'cdstatus' => 'N',
	'nmsearch' => 'CUBS',
	'nmclub' => 'Cubs',
	'nmfull' => 'CUBS',
	'ftlocation' => 'Harderberg',
	'ftaddress' => 'Europaweg',
	'nmcity' => 'HARDERBERG',
	'ftphone' => '0523-265821',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '67',
	'cdstatus' => 'N',
	'nmsearch' => 'HOOFD',
	'nmclub' => 'Hoofdd.Pioniers',
	'nmfull' => 'MINOLTA PIONIERS',
	'ftlocation' => 'Hoofddorp',
	'ftfield' => 'Sportpark \'Toolenburg\'',
	'ftaddress' => 'Hoofdweg 865',
	'ftpostalcode' => '2131MB',
	'nmcity' => 'HOOFDDORP',
	'ftphone' => '023-5613557',
	'is_featured' => '1',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '68',
	'cdstatus' => 'N',
	'nmsearch' => 'HYGIE',
	'nmclub' => 'Hygiea',
	'nmfull' => 'HYGIÃƒÂ«A',
	'ftlocation' => 'Den Haag',
	'ftfield' => 'Stokroosveld',
	'ftaddress' => 'Stokroosstraat',
	'ftpostalcode' => '2565RT',
	'nmcity' => 'DEN HAAG',
	'ftphone' => '070-3636671',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '69',
	'cdstatus' => 'N',
	'nmsearch' => 'JEKA',
	'nmclub' => 'Jeka',
	'nmfull' => 'h.s.c. JEKA',
	'ftlocation' => 'Breda',
	'ftfield' => 'Sportcomplex \'Lage Kant\'',
	'ftaddress' => 'Langveld',
	'nmcity' => 'BREDA',
	'ftphone' => '076-5223274',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '70',
	'cdstatus' => 'N',
	'nmsearch' => 'KENNE',
	'nmclub' => 'Kennemerland',
	'nmfull' => 'h.s.c. KENNEMERLAND',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Pim Muliersportpark',
	'ftpostalcode' => '2024BW',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5272678',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '71',
	'cdstatus' => 'N',
	'nmsearch' => 'KICKE',
	'nmclub' => 'Kickers',
	'nmfull' => 'b.s.v. KICKERS',
	'ftlocation' => 'Waalwijk',
	'ftfield' => 'Sportpark Eikendonk',
	'nmcity' => 'WAALWIJK',
	'ftphone' => '0416-340929',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '72',
	'cdstatus' => 'N',
	'nmsearch' => 'KINHB',
	'nmclub' => 'Kinheim HB',
	'nmfull' => 'HOME PIZZA KINHEIM',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Gem. Sportpark Badmintonpad',
	'ftaddress' => 'Badmintonpad',
	'ftpostalcode' => '2023BT',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5260021',
	'is_featured' => '1',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '73',
	'cdstatus' => 'N',
	'nmsearch' => 'KNUPP',
	'nmclub' => 'Knuppelaars',
	'nmfull' => 'DE KNUPPELAARS',
	'ftlocation' => 'Rosmalen',
	'ftaddress' => 'P. de Gorterstraat',
	'nmcity' => 'ROSMALEN',
	'ftphone' => '073-5217968',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '74',
	'cdstatus' => 'N',
	'nmsearch' => 'KOKOL',
	'nmclub' => 'Kokoloshi',
	'nmfull' => 's.v. KOKOLOSHI',
	'ftlocation' => 'Den Haag',
	'ftfield' => 'Stokroosveld',
	'ftaddress' => 'Stokroosstraat',
	'ftpostalcode' => '2565RT',
	'nmcity' => 'DEN HAAG',
	'ftphone' => '070-3636671',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '75',
	'cdstatus' => 'N',
	'nmsearch' => 'LAAKK',
	'nmclub' => 'Laakkwartier',
	'nmfull' => 'h.v.v. LAAKKWARTIER',
	'ftlocation' => 'Den Haag',
	'ftaddress' => 'Jan van Beersstraat',
	'nmcity' => 'DEN HAAG',
	'ftphone' => '070-3938341',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '76',
	'cdstatus' => 'N',
	'nmsearch' => 'LROCK',
	'nmclub' => 'Little Rock',
	'nmfull' => 'OVERAMSTEL-LITTLE ROCK',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark \'Middenmeer\'',
	'ftaddress' => 'Verlengde Radioweg (Kruislaan)',
	'nmcity' => 'AMSTERDAM',
	'ftphone' => '020-6925754',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '77',
	'cdstatus' => 'N',
	'nmsearch' => 'SAINT',
	'nmclub' => 'Saints',
	'nmfull' => 'r.k.s.v. SAINTS',
	'ftlocation' => 'Rotterdam',
	'ftfield' => 'Sportcomplex \'Duyvestein\'',
	'nmcity' => 'ROTTERDAM',
	'ftphone' => '010-4222113',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '78',
	'cdstatus' => 'N',
	'nmsearch' => 'WADHO',
	'nmclub' => 'Badhoevedorp',
	'nmfull' => 's.c. BADHOEVEDORP',
	'ftlocation' => 'Badhoevedorp',
	'ftfield' => 'S.C. Badhoevedorp',
	'ftaddress' => 'Wijnmalenstraat',
	'ftpostalcode' => '1170AB',
	'nmcity' => 'BADHOEVEDORP',
	'ftphone' => '020-6592500',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '79',
	'cdstatus' => 'N',
	'nmsearch' => 'MAASS',
	'nmclub' => 'Maasstricht',
	'nmfull' => 'h.s.c. MAASSTRICHT',
	'ftlocation' => 'Maasstricht',
	'ftfield' => 'Sportpark West',
	'nmcity' => 'MAASSTRICHT',
	'ftphone' => '043-3436447',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '80',
	'cdstatus' => 'N',
	'nmsearch' => 'METEO',
	'nmclub' => 'Meteoor',
	'nmfull' => 's.v. DE METEOOR',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark Perenpad',
	'ftaddress' => 'Perenpad',
	'nmcity' => 'AMSTERDAM-NOORD',
	'ftphone' => '020-6315375',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '81',
	'cdstatus' => 'N',
	'nmsearch' => 'MOORF',
	'nmclub' => 'Moorfielders',
	'nmfull' => 'b.s.v. MOORFIELDERS',
	'ftlocation' => 'Ede',
	'ftfield' => 'Sportpark \'De Hoekelumse Eng\'',
	'ftaddress' => 'Sportparkweg 16',
	'ftpostalcode' => '6717LD',
	'nmcity' => 'EDE',
	'ftphone' => '0318-622551',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '82',
	'cdstatus' => 'N',
	'nmsearch' => 'GOPHE',
	'nmclub' => 'Gophers',
	'nmfull' => 'GOPHERS',
	'ftlocation' => 'Maassluis',
	'ftaddress' => 'Steendijkpolder',
	'ftpostalcode' => '3146TA',
	'nmcity' => 'MAASSLUIS',
	'ftphone' => '010-5917051',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '83',
	'cdstatus' => 'N',
	'nmsearch' => 'MULO',
	'nmclub' => 'MULO',
	'nmfull' => 'M.U.L.O.',
	'ftlocation' => 'Helmond',
	'ftfield' => 'Sportpark \'Rivierensingel\'',
	'ftaddress' => 'Rivierensingel',
	'ftpostalcode' => '5704KE',
	'nmcity' => 'HELMOND',
	'ftphone' => '0492-514970',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '84',
	'cdstatus' => 'N',
	'nmsearch' => 'ORIOL',
	'nmclub' => 'R\'dam Orioles',
	'nmfull' => 'THE ROTTERDAM ORIOLES',
	'ftlocation' => 'Rotterdam',
	'ftaddress' => 'Beekweg 48',
	'ftpostalcode' => '3045PA',
	'nmcity' => 'ROTTERDAM',
	'ftphone' => '010-4677518',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '85',
	'cdstatus' => 'N',
	'nmsearch' => 'NEPTU',
	'nmclub' => 'Neptunus',
	'nmfull' => 's.c. NEPTUNUS',
	'ftlocation' => 'Rotterdam',
	'ftfield' => 'Honkbalstadion Neptunus',
	'ftaddress' => 'Abraham van Stolkweg 31',
	'ftpostalcode' => '3041JA',
	'nmcity' => 'ROTTERDAM',
	'ftphone' => '010-4375369',
	'is_featured' => '1',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '86',
	'cdstatus' => 'N',
	'nmsearch' => 'VENNE',
	'nmclub' => 'Vennep Flyers',
	'nmfull' => 'h.s.v. VENNEP FLYERS',
	'ftlocation' => 'Nieuw Vennep',
	'ftfield' => 'Sportcomplex \'Oosterdreef\'',
	'nmcity' => 'NIEUW-VENNEP',
	'ftphone' => '0252-620266',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '87',
	'cdstatus' => 'N',
	'nmsearch' => 'NISC',
	'nmclub' => 'NISC \'71',
	'nmfull' => 'N.I.S.C. \'71',
	'ftlocation' => 'Nijmegen',
	'ftfield' => 'Sportpark \'Lindenholt\'',
	'ftaddress' => 'Weteringweg 50',
	'ftpostalcode' => '6546AJ',
	'nmcity' => 'LINDENHOLT',
	'ftphone' => '024-3784178',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '88',
	'cdstatus' => 'N',
	'nmsearch' => 'NUENE',
	'nmclub' => 'Nuenen',
	'nmfull' => 'h.s.c. NUENEN',
	'ftlocation' => 'Nuenen',
	'ftfield' => 'Sportpark \'De Lissevoort\'',
	'nmcity' => 'NUENEN',
	'ftphone' => '040-2840566',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '89',
	'cdstatus' => 'N',
	'nmsearch' => 'ODIZ',
	'nmclub' => 'Odiz Frogs',
	'nmfull' => 's.v. ODIZ FROGS',
	'ftlocation' => 'Zaandam',
	'ftfield' => 'Sportpark \'\'t Kalf\'',
	'nmcity' => 'ZAANDAM',
	'ftphone' => '075-6354618',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '90',
	'cdstatus' => 'N',
	'nmsearch' => 'OGHB',
	'nmclub' => 'Onze Gezellen',
	'nmfull' => 'r.k.h.v. ONZE GEZELLEN',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Sportpark Vlietweg',
	'ftaddress' => 'Vlietweg',
	'ftpostalcode' => '2026BZ',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5373967',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '91',
	'cdstatus' => 'N',
	'nmsearch' => 'OVVO',
	'nmclub' => 'OVVO',
	'nmfull' => 'a.s.v. O.V.V.O.',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark \'Middenmeer\'',
	'ftaddress' => 'Verlengde Radioweg (Kruislaan)',
	'ftpostalcode' => '1098NG',
	'nmcity' => 'AMSTERDAM',
	'ftphone' => '020-6630516',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '92',
	'cdstatus' => 'N',
	'nmsearch' => 'PEATT',
	'nmclub' => 'Peattwn Peppers',
	'nmfull' => 'THE PEATTOWN PEPPERS',
	'ftlocation' => 'Heerenveen',
	'ftaddress' => 'Buitenbaan',
	'nmcity' => 'HEERENVEEN',
	'ftphone' => '0513-626333',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '93',
	'cdstatus' => 'N',
	'nmsearch' => 'PHANT',
	'nmclub' => 'Phantoms',
	'nmfull' => 'b.s.c. PHANTOMS',
	'ftlocation' => 'Weert',
	'ftfield' => 'Sportpark \'Boshoven\'',
	'ftaddress' => 'Vrakkerveld 7',
	'nmcity' => 'WEERT',
	'ftphone' => '0495-521997',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '94',
	'cdstatus' => 'N',
	'nmsearch' => 'PHOEN',
	'nmclub' => 'Phoenix ZC',
	'nmfull' => 's.v. PHOENIX Z.C.',
	'ftlocation' => 'Zeist',
	'ftfield' => 'Sportveld Koeburgweg 1',
	'ftaddress' => 'Driebergseweg 20',
	'ftpostalcode' => '3709JD',
	'nmcity' => 'ZEIST',
	'ftphone' => '030-6921248',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '95',
	'cdstatus' => 'N',
	'nmsearch' => 'PINGU',
	'nmclub' => 'Pinguins',
	'nmfull' => 'h.s.c. DE PINGUINS',
	'ftlocation' => 'Heemstede',
	'ftfield' => 'Heemsteeds Sportpark',
	'ftaddress' => 'Sportparklaan, Verl. Javalaan',
	'nmcity' => 'HEEMSTEDE',
	'ftphone' => '023-5286751',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '96',
	'cdstatus' => 'N',
	'nmsearch' => 'PINOS',
	'nmclub' => 'Pino\'s',
	'nmfull' => 'DE PINO\'S',
	'ftlocation' => 'IJmuiden',
	'ftfield' => 'Sportpark \'Zeewijk\'',
	'nmcity' => 'IJMUIDEN',
	'ftphone' => '0255-522264',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '97',
	'cdstatus' => 'N',
	'nmsearch' => 'PIONE',
	'nmclub' => 'Pioneers',
	'nmfull' => 's.c. THE PIONEERS',
	'ftlocation' => 'Assen',
	'ftfield' => 'Sportpark \'Dijkveld\'',
	'ftaddress' => 'Dijkveldpad 2',
	'ftpostalcode' => '9403TC',
	'nmcity' => 'ASSEN',
	'ftphone' => '0592-341094',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '98',
	'cdstatus' => 'N',
	'nmsearch' => 'PIRAT',
	'nmclub' => 'Pirates',
	'nmfull' => 's.v. PIRATES',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark \'Jan van Galen\'',
	'ftaddress' => 'Jan van Galenstraat',
	'nmcity' => 'AMSTERDAM',
	'ftphone' => '020-6162151',
	'is_featured' => '1',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '99',
	'cdstatus' => 'N',
	'nmsearch' => 'PSV',
	'nmclub' => 'PSV',
	'nmfull' => 'P.S.V.',
	'ftlocation' => 'Eindhoven',
	'ftfield' => 'Sportpark \'De Heihoef\'',
	'ftaddress' => 'Roostenlaan',
	'nmcity' => 'EINDHOVEN',
	'ftphone' => '040-2117750',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '100',
	'cdstatus' => 'N',
	'nmsearch' => 'QUICK',
	'nmclub' => 'Quick',
	'nmfull' => 'b.s.c. QUICK',
	'ftlocation' => 'Amersfoort',
	'ftfield' => 'Sportpark \'Dorrestein\'',
	'ftaddress' => 'Dorresteinsesteeg',
	'ftpostalcode' => '3817GC',
	'nmcity' => 'AMERSFOORT',
	'ftphone' => '033-4613883',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '101',
	'cdstatus' => 'N',
	'nmsearch' => 'RCH',
	'nmclub' => 'RCH',
	'nmfull' => 'R.C.H.',
	'ftlocation' => 'Heemstede',
	'ftfield' => 'Heemsteedse Sportparken',
	'ftaddress' => 'Ringvaartlaan',
	'nmcity' => 'HEEMSTEDE',
	'ftphone' => '023-5284388',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '102',
	'cdstatus' => 'N',
	'nmsearch' => 'REDLI',
	'nmclub' => 'Red Lions',
	'nmfull' => 'r.h.s.v. RED LIONS',
	'ftlocation' => 'Rijswijk',
	'ftfield' => 'Sportpark \'Prinses Irene\'',
	'ftaddress' => 'Schaapweg',
	'ftpostalcode' => '2285SP',
	'nmcity' => 'RIJSWIJK',
	'ftphone' => '070-3941368',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '103',
	'cdstatus' => 'N',
	'nmsearch' => 'RANGE',
	'nmclub' => 'Rangers',
	'nmfull' => 'A.A. RANGERS',
	'ftlocation' => 'Eindhoven',
	'ftfield' => 'Sportcomplex Tech. Univ.',
	'ftaddress' => 'Lidwinastraat 1',
	'nmcity' => 'EINDHOVEN',
	'ftphone' => '040-2437671',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '104',
	'cdstatus' => 'N',
	'nmsearch' => 'RANGE',
	'nmclub' => 'Rangers',
	'nmfull' => 'b.s.c. THE RANGERS',
	'ftlocation' => 'Schagen',
	'ftfield' => 'Sportcomplex \'Groenoord\'',
	'ftaddress' => 'Groeneweg',
	'ftpostalcode' => '1740AD',
	'nmcity' => 'SCHAGEN',
	'ftphone' => '0224-213370',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '105',
	'cdstatus' => 'N',
	'nmsearch' => 'RIDDE',
	'nmclub' => 'Ridderk Rowdies',
	'nmfull' => 'RIDDERKERK ROWDIES',
	'ftlocation' => 'Ridderkerk',
	'ftfield' => 'Sportpark \'Oosterpark\'',
	'ftaddress' => 'Oosterparkweg 7',
	'ftpostalcode' => '2986AE',
	'nmcity' => 'RIDDERKERK',
	'ftphone' => '0180-430240',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '106',
	'cdstatus' => 'N',
	'nmsearch' => 'ROBUR',
	'nmclub' => 'Robur \'58',
	'nmfull' => 'ROBUR \'58',
	'ftlocation' => 'Apeldoorn',
	'ftfield' => 'Sportpark \'Orderbos\'',
	'nmcity' => 'APELDOORN',
	'ftphone' => '055-3553474',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '107',
	'cdstatus' => 'N',
	'nmsearch' => 'ROEF',
	'nmclub' => 'Roef!',
	'nmfull' => 'ROEF!',
	'ftlocation' => 'Moergestel',
	'ftfield' => 'Stokeind',
	'ftpostalcode' => '5066XA',
	'nmcity' => 'MOERGESTEL',
	'ftphone' => '013-5131966',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '108',
	'cdstatus' => 'N',
	'nmsearch' => 'ROOSW',
	'nmclub' => 'Rooswijk',
	'nmfull' => 'h.s.v. ROOSWIJK',
	'ftlocation' => 'Velsen-Noord',
	'ftfield' => 'Sportpark Rooswijk',
	'ftpostalcode' => '1951HH',
	'nmcity' => 'VELSEN-NOORD',
	'ftphone' => '0251-224605',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '109',
	'cdstatus' => 'N',
	'nmsearch' => 'RUN',
	'nmclub' => 'Run\'71',
	'nmfull' => 'h.s.v. RUN\'71',
	'ftlocation' => 'Oldenzaal',
	'ftaddress' => 'Vondellaan',
	'nmcity' => 'OLDENZAAL',
	'ftphone' => '0541-513944',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '110',
	'cdstatus' => 'N',
	'nmsearch' => 'SAT',
	'nmclub' => 'SAT Tigers',
	'nmfull' => 'S.A.T. TIGERS',
	'ftlocation' => 'Tilburg',
	'ftfield' => 'Sportpark Tilburg',
	'ftaddress' => 'Goirleseweg',
	'ftpostalcode' => '5026PC',
	'nmcity' => 'TILBURG',
	'ftphone' => '013-5352924',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '111',
	'cdstatus' => 'N',
	'nmsearch' => 'SCHIE',
	'nmclub' => 'Schiedam',
	'nmfull' => 's.v. & h.v. SCHIEDAM',
	'ftlocation' => 'Schiedam',
	'ftfield' => 'Sportpark \'Harga\'',
	'ftaddress' => 'Sportlaan',
	'ftpostalcode' => '3118JC',
	'nmcity' => 'SCHIEDAM',
	'ftphone' => '010-4701546',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '112',
	'cdstatus' => 'N',
	'nmsearch' => 'SCHOT',
	'nmclub' => 'Schoten',
	'nmfull' => 'h.c. SCHOTEN',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'v.d. Aartsportpark',
	'ftaddress' => 'Vondelweg',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5375203',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '113',
	'cdstatus' => 'N',
	'nmsearch' => 'SEAGU',
	'nmclub' => 'Seagulls',
	'nmfull' => 'b.s.v. THE SEAGULLS',
	'ftlocation' => 'Middenmeer',
	'ftaddress' => 'Sportweg',
	'ftpostalcode' => '1775ZG',
	'nmcity' => 'MIDDENMEER',
	'ftphone' => '0227-501452',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '114',
	'cdstatus' => 'N',
	'nmsearch' => 'SHELL',
	'nmclub' => 'Shell',
	'nmfull' => 'S.H.E.L.L.',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark SHELL',
	'ftaddress' => 'Valentijnkade',
	'ftpostalcode' => '1095JL',
	'nmcity' => 'AMSTERDAM',
	'ftphone' => '020-6654972',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '115',
	'cdstatus' => 'N',
	'nmsearch' => 'SHOCK',
	'nmclub' => 'Shock',
	'nmfull' => 'S.H.O.C.K.',
	'ftlocation' => 'Kampen',
	'ftfield' => 'Sportpark \'Hagenbroek\'',
	'ftpostalcode' => '8260AH',
	'nmcity' => 'KAMPEN',
	'ftphone' => '038-3317193',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '116',
	'cdstatus' => 'N',
	'nmsearch' => 'SITTA',
	'nmclub' => 'Sittard Condors',
	'nmfull' => 'h.s.c. SITTARD CONDORS',
	'ftlocation' => 'Sittard',
	'ftfield' => 'Nationaal Sportcentrum Sittard',
	'ftpostalcode' => '6130AH',
	'nmcity' => 'SITTARD',
	'ftphone' => '046-4581694',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '117',
	'cdstatus' => 'N',
	'nmsearch' => 'SPAAR',
	'nmclub' => 'Spaarnwoude',
	'nmfull' => 's.v. SPAARNWOUDE',
	'ftlocation' => 'Spaarndam',
	'ftfield' => 'Sportpark Spaarndam',
	'ftaddress' => 'Ringweg',
	'ftpostalcode' => '2064KE',
	'nmcity' => 'SPAARNDAM',
	'ftphone' => '023-5372904',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '118',
	'cdstatus' => 'N',
	'nmsearch' => 'SPARK',
	'nmclub' => 'Sparks',
	'nmfull' => 'SPARKS',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Noordersportpark',
	'ftaddress' => 'Mr. J. Gerritszlaan',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5264110',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '119',
	'cdstatus' => 'N',
	'nmsearch' => 'SPARTA',
	'nmclub' => 'Sparta',
	'nmfull' => 'r.v. & a.v. SPARTA',
	'ftlocation' => 'Rotterdam',
	'ftfield' => 'Sportpark \'Nieuw Vreelust\'',
	'ftaddress' => 'Spaanseweg 1',
	'ftpostalcode' => '3028HW',
	'nmcity' => 'ROTTERDAM',
	'ftphone' => '010-4151145',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '120',
	'cdstatus' => 'N',
	'nmsearch' => 'ANIMA',
	'nmclub' => 'Animals',
	'nmfull' => 'THE ANIMALS',
	'ftlocation' => 'Dieren',
	'ftfield' => 'Sportpark \'Nieuwland\'',
	'nmcity' => 'DIEREN',
	'ftphone' => '0313-414971',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '121',
	'cdstatus' => 'N',
	'nmsearch' => 'SPARTAAN',
	'nmclub' => 'Spartaan',
	'nmfull' => 'k.h.s.v. DE SPARTAAN',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark \'Ookmeer\'',
	'ftaddress' => 'Herman Bonpad 1',
	'ftpostalcode' => '1067SN',
	'nmcity' => 'AMSTERDAM',
	'ftphone' => '020-6149950',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '122',
	'cdstatus' => 'N',
	'nmsearch' => 'STAGS',
	'nmclub' => 'Stags',
	'nmfull' => 'THE STAGS',
	'ftlocation' => 'Etten-Leur',
	'ftfield' => 'Sportpark \'De Lage Banken\'',
	'ftpostalcode' => '4871ZA',
	'nmcity' => 'ETTEN-LEUR',
	'ftphone' => '076-5022919',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '123',
	'cdstatus' => 'N',
	'nmsearch' => 'STARL',
	'nmclub' => 'Starlights',
	'nmfull' => 'b.s.v. STARLIGHTS',
	'ftlocation' => 'Schijndel',
	'ftfield' => 'Sportcomplex \'De Leemput\'',
	'ftaddress' => 'Oude Molenheide 12',
	'ftpostalcode' => '5480AB',
	'nmcity' => 'SCHIJNDEL',
	'ftphone' => '073-5498418',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '124',
	'cdstatus' => 'N',
	'nmsearch' => 'STORK',
	'nmclub' => 'Storks',
	'nmfull' => 'h.s.v. STORKS',
	'ftlocation' => 'Den Haag',
	'ftfield' => 'Sportpark \'Kijkduin\'',
	'ftaddress' => 'Machiel Vrijenhoeklaan',
	'ftpostalcode' => '2555NA',
	'nmcity' => 'DEN HAAG',
	'ftphone' => '070-3234151',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '125',
	'cdstatus' => 'N',
	'nmsearch' => 'STUDS',
	'nmclub' => 'Studs',
	'nmfull' => 'e.s.h.v. THE STUDS',
	'ftlocation' => 'Eindhoven',
	'ftfield' => 'Burg. van Engeland Sportpark',
	'ftaddress' => 'Jozef IsraÃƒÂ«lslaan',
	'nmcity' => 'EINDHOVEN',
	'ftphone' => '040-2462827',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '126',
	'cdstatus' => 'N',
	'nmsearch' => 'TERHB',
	'nmclub' => 'Terrasvogels',
	'nmfull' => 'TERRASVOGELS',
	'ftlocation' => 'Santpoort',
	'ftfield' => 'Sportpark \'De Elta\'',
	'ftpostalcode' => '2082XM',
	'nmcity' => 'SANTPOORT',
	'ftphone' => '023-5378652',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '127',
	'cdstatus' => 'N',
	'nmsearch' => 'TEX',
	'nmclub' => 'Tex Town Tigers',
	'nmfull' => 'TEX TOWN TIGERS',
	'ftlocation' => 'Enschede',
	'ftfield' => 'Stadsveld Noord',
	'ftaddress' => 'Corn. Troostlaan 15',
	'ftpostalcode' => '7545BT',
	'nmcity' => 'ENSCHEDE',
	'ftphone' => '053-4323599',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '128',
	'cdstatus' => 'N',
	'nmsearch' => 'THAME',
	'nmclub' => 'Thamen',
	'nmfull' => 'h.s.v. THAMEN',
	'ftlocation' => 'Uithoorn',
	'ftfield' => 'Sportpark \'Vuurlijn\'',
	'nmcity' => 'UITHOORN',
	'ftphone' => '0297-564400',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '129',
	'cdstatus' => 'N',
	'nmsearch' => 'THB',
	'nmclub' => 'THB',
	'nmfull' => 'T.H.B.',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Sportcomplex \'Eindenhout\'',
	'ftaddress' => 'Van Hogendorpstraat',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5317776',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '130',
	'cdstatus' => 'N',
	'nmsearch' => 'TILBU',
	'nmclub' => 'Tilburg',
	'nmfull' => 'h.s.c. TILBURG',
	'ftlocation' => 'Tilburg',
	'ftfield' => 'Gem. Sportpark',
	'ftaddress' => 'Goirleseweg',
	'ftpostalcode' => '5026PC',
	'nmcity' => 'TILBURG',
	'ftphone' => '013-5352924',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '131',
	'cdstatus' => 'N',
	'nmsearch' => 'TWINS',
	'nmclub' => 'Twins',
	'nmfull' => 'GAMBRO TWINS',
	'ftlocation' => 'Oosterhout',
	'ftfield' => 'Sportpark \'De Slotbosse Toren\'',
	'ftpostalcode' => '4907EA',
	'nmcity' => 'OOSTERHOUT',
	'ftphone' => '0162-433760',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '132',
	'cdstatus' => 'N',
	'nmsearch' => 'TYBB',
	'nmclub' => 'TYBB',
	'nmfull' => 'T.Y.B.B.',
	'ftlocation' => 'Haarlem',
	'ftaddress' => 'Schalkwijkerweg',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5338606',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '133',
	'cdstatus' => 'N',
	'nmsearch' => 'URBAN',
	'nmclub' => 'Urbanus',
	'nmfull' => 'h.b.s.v. URBANUS',
	'ftlocation' => 'Hoorn',
	'ftfield' => 'Risdam Noord',
	'ftaddress' => 'Kerketuin',
	'nmcity' => 'HOORN',
	'ftphone' => '0229-233292',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '134',
	'cdstatus' => 'N',
	'nmsearch' => 'UTREC',
	'nmclub' => 'Utrecht',
	'nmfull' => 'b.s.c. UTRECHT',
	'ftlocation' => 'Utrecht',
	'ftfield' => 'Sportpark \'Welgelegen\'',
	'ftaddress' => 'Adm. Helfrichlaan 20',
	'ftpostalcode' => '3527KV',
	'nmcity' => 'UTRECHT',
	'ftphone' => '030-2945828',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '135',
	'cdstatus' => 'N',
	'nmsearch' => 'UVV',
	'nmclub' => 'UVV',
	'nmfull' => 'U.V.V.-RED LIONS',
	'ftlocation' => 'Utrecht',
	'ftfield' => 'Sportpark \'J.C. Verthoren\'',
	'ftpostalcode' => '3541BE',
	'nmcity' => 'UTRECHT',
	'ftphone' => '030-2932702',
	'is_featured' => '1',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '136',
	'cdstatus' => 'N',
	'nmsearch' => 'REDCA',
	'nmclub' => 'Red Caps Venray',
	'nmfull' => 'RED CAPS VENRAY',
	'ftlocation' => 'Venray',
	'ftfield' => 'Sportpark \'De WieÃƒÂ«n\'',
	'nmcity' => 'VENRAY',
	'ftphone' => '0478-512140',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '137',
	'cdstatus' => 'N',
	'nmsearch' => 'VIKIN',
	'nmclub' => 'Vikingen',
	'nmfull' => 'h.b.s.v. VIKINGEN',
	'ftlocation' => 'Den Helder',
	'ftfield' => '\'De Donkere Duinen\'',
	'nmcity' => 'DEN HELDER',
	'ftphone' => '0223-614435',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '138',
	'cdstatus' => 'N',
	'nmsearch' => 'VIPS',
	'nmclub' => 'VIPS',
	'nmfull' => 'V.I.P.S.',
	'ftlocation' => 'Maartensdijk',
	'ftfield' => 'Sportcomplex \'F.J.H. van Eck\'',
	'ftaddress' => 'Dierenriem',
	'nmcity' => 'MAARTENSDIJK',
	'ftphone' => '0346-214145',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '139',
	'cdstatus' => 'N',
	'nmsearch' => 'VITES',
	'nmclub' => 'Vitesse\'22',
	'nmfull' => 'r.k.s.v. VITESSE\'22',
	'ftlocation' => 'Castricum',
	'ftfield' => 'Sportpark \'Puikman 3\'',
	'nmcity' => 'CASTRICUM',
	'ftphone' => '0251-652061',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '140',
	'cdstatus' => 'N',
	'nmsearch' => 'HOLY',
	'nmclub' => 'Vlaardingen Holy',
	'nmfull' => 's.c. VLAARDINGEN-HOLY',
	'ftlocation' => 'Vlaardingen',
	'ftfield' => 'Sportcomplex Zwaluwenlaan',
	'ftaddress' => 'Zwaluwenlaan 480',
	'ftpostalcode' => '3136VH',
	'nmcity' => 'VLAARDINGEN',
	'ftphone' => '010-4749196',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '141',
	'cdstatus' => 'N',
	'nmsearch' => 'VOLEW',
	'nmclub' => 'Volewijckers',
	'nmfull' => 'DE VOLEWIJCKERS',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark \'Buiksloterbanne\'',
	'ftpostalcode' => '1034ZK',
	'nmcity' => 'AMSTERDAM',
	'ftphone' => '020-6316433',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '142',
	'cdstatus' => 'N',
	'nmsearch' => 'VUC',
	'nmclub' => 'VUC',
	'nmfull' => 'V.U.C.',
	'ftlocation' => 'Den Haag',
	'ftaddress' => 'Het Kleine Loo 1',
	'ftpostalcode' => '2592BW',
	'nmcity' => 'DEN HAAG',
	'ftphone' => '070-3858018',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '143',
	'cdstatus' => 'N',
	'nmsearch' => 'WASSE',
	'nmclub' => 'Wassenaar',
	'nmfull' => 's.v. WASSENAAR',
	'ftlocation' => 'Wassenaar',
	'ftfield' => 'Sportpark \'Kerkehout\'',
	'ftaddress' => 'Charlottestraat 7',
	'ftpostalcode' => '2245VW',
	'nmcity' => 'WASSENAAR',
	'ftphone' => '070-5179748',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '144',
	'cdstatus' => 'N',
	'nmsearch' => 'WHSC',
	'nmclub' => 'WHSC',
	'nmfull' => 'W.H.S.C.',
	'ftlocation' => 'Winschoten',
	'ftfield' => 'Sportcomplex Stadsparklaan',
	'ftaddress' => 'Mr. D.U. Stikkerlaan',
	'nmcity' => 'WINSCHOTEN',
	'ftphone' => '0597-423117',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '145',
	'cdstatus' => 'N',
	'nmsearch' => 'WSB',
	'nmclub' => 'WSB',
	'nmfull' => 'W.S.B.',
	'ftlocation' => 'Apeldoorn',
	'ftfield' => 'Sportpark \'De Maten\'',
	'ftaddress' => 'Kaartenmakershoeve 108',
	'nmcity' => 'APELDOORN',
	'ftphone' => '055-5337777',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '146',
	'cdstatus' => 'N',
	'nmsearch' => 'WHALE',
	'nmclub' => 'Whalers',
	'nmfull' => 'W.S.V.\'30 THE WHALERS',
	'ftlocation' => 'Wormer',
	'ftfield' => 'WSV-Wormer',
	'ftaddress' => 'Dorpsstraat 206 B',
	'nmcity' => 'WORMER',
	'ftphone' => '075-6423004',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '147',
	'cdstatus' => 'N',
	'nmsearch' => 'WIJCK',
	'nmclub' => 'Wijck Lions',
	'nmfull' => 'b.s.v. WIJCK LIONS',
	'ftlocation' => 'Wijk bij Duurstede',
	'ftfield' => 'Sportcomplex \'MariÃƒÂ«nhoeve\'',
	'ftaddress' => 'Lekdijk Oost 12',
	'ftpostalcode' => '3961MB',
	'nmcity' => 'WIJK BIJ DUURSTEDE',
	'ftphone' => '0343-574253',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '148',
	'cdstatus' => 'N',
	'nmsearch' => 'ZEEUW',
	'nmclub' => 'Zeeuwse Honk',
	'nmfull' => 'h.s.v. HET ZEEUWSE HONK',
	'ftlocation' => 'Terneuzen',
	'ftfield' => 'Sportpark \'De Oude Vaart\'',
	'nmcity' => 'TERNEUZEN',
	'ftphone' => '0115-616458',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '149',
	'cdstatus' => 'N',
	'nmsearch' => 'ZUIDV',
	'nmclub' => 'Zuidvogels',
	'nmfull' => 'b.s.v. DE ZUIDVOGELS',
	'ftlocation' => 'Huizen',
	'ftfield' => 'Sportpark \'Meentweide\'',
	'ftpostalcode' => '1274VT',
	'nmcity' => 'HUIZEN',
	'ftphone' => '035-5255220',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '150',
	'cdstatus' => 'N',
	'nmsearch' => 'ZWIJN',
	'nmclub' => 'Zwijndrecht',
	'nmfull' => 'h.s.v. ZWIJNDRECHT',
	'ftlocation' => 'Zwijndrecht',
	'ftfield' => 'Sportcomplex \'Bakestein\'',
	'ftpostalcode' => '3335KG',
	'nmcity' => 'ZWIJNDRECHT',
	'ftphone' => '078-6101379',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '151',
	'cdstatus' => 'N',
	'nmsearch' => 'EDS',
	'nmclub' => 'EDS',
	'nmfull' => 'E.D.S.',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark \'De Eendracht\'',
	'ftpostalcode' => '1067HR',
	'nmcity' => 'AMSTERDAM',
	'ftphone' => '020-6114400',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '152',
	'cdstatus' => 'N',
	'nmsearch' => 'VOLLE',
	'nmclub' => 'Volle Bak',
	'nmfull' => 'VOLLE BAK',
	'ftlocation' => 'Leiden',
	'ftfield' => 'Sportpark \'Leidse Hout\'',
	'ftaddress' => 'Anth. Duycklaan',
	'nmcity' => 'LEIDEN',
	'ftphone' => '071-5176457',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '153',
	'cdstatus' => 'N',
	'nmsearch' => 'ASTRO',
	'nmclub' => 'Astros',
	'nmfull' => 'ASTROS',
	'ftlocation' => 'Heerde',
	'ftaddress' => 'Kommerseweg 2',
	'nmcity' => 'HEERDE',
	'ftphone' => '0578-694880',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '154',
	'cdstatus' => 'N',
	'nmsearch' => 'BLSTA',
	'nmclub' => 'Blue Stars',
	'nmfull' => 'h.s.v. BLUE STARS',
	'ftlocation' => 'Numansdorp',
	'ftaddress' => 'Meestooflaan',
	'nmcity' => 'NUMANSDORP',
	'ftphone' => '0186-653233',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '155',
	'cdstatus' => 'N',
	'nmsearch' => 'WOMBA',
	'nmclub' => 'Wombats',
	'nmfull' => 'u.h.s.v. THE WOMBATS',
	'ftlocation' => 'Utrecht',
	'ftfield' => 'Sportpark \'Weltevreden\'',
	'ftpostalcode' => '3731AL',
	'nmcity' => 'DE BILT',
	'ftphone' => '030-2204575',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '156',
	'cdstatus' => 'N',
	'nmsearch' => 'REDCA',
	'nmclub' => 'Red Caps',
	'nmfull' => 'THE RED CAPS',
	'ftlocation' => 'Leusden',
	'ftfield' => 'Vallei Sportpark',
	'ftpostalcode' => '3831JN',
	'nmcity' => 'LEUSDEN',
	'ftphone' => '033-4941501',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '157',
	'cdstatus' => 'N',
	'nmsearch' => 'NORTH',
	'nmclub' => 'Northern Stars',
	'nmfull' => 'h.s.v. NORTHERN STARS',
	'ftlocation' => 'Leeuwarden',
	'ftfield' => 'Sportcomplex \'\'t Kalverdijkje\'',
	'ftaddress' => 'Kalverdijkje 85',
	'ftpostalcode' => '8924JJ',
	'nmcity' => 'LEEUWARDEN',
	'ftphone' => '058-2666496',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '158',
	'cdstatus' => 'N',
	'nmsearch' => 'GEINO',
	'nmclub' => 'Geinoord',
	'nmfull' => 's.v. GEINOORD',
	'ftlocation' => 'Nieuwegein',
	'ftfield' => 'Sportpark \'Parkhout\'',
	'nmcity' => 'NIEUWEGEIN',
	'ftphone' => '030-6080697',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '159',
	'cdstatus' => 'N',
	'nmsearch' => 'AMVJ',
	'nmclub' => 'AMVJ/US',
	'nmfull' => 'A.M.V.J./U.S. COMBINATIE',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark \'Het Loopveld\'',
	'ftaddress' => 'Kalfjeslaan',
	'ftpostalcode' => '1183SZ',
	'nmcity' => 'AMSTELVEEN',
	'ftphone' => '020-6457248',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '160',
	'cdstatus' => 'N',
	'nmsearch' => 'POWER',
	'nmclub' => 'Power \'66',
	'nmfull' => 'POWER \'66',
	'ftlocation' => 'Den Haag',
	'ftfield' => 'Stokroosveld',
	'ftaddress' => 'Stokroosstraat',
	'nmcity' => 'DEN HAAG',
	'ftphone' => '070-3639093',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '161',
	'cdstatus' => 'N',
	'nmsearch' => 'ORIOL',
	'nmclub' => 'Orioles',
	'nmfull' => 's.v. THE ORIOLES',
	'ftlocation' => 'Veghel',
	'nmcity' => 'VEGHEL',
	'ftphone' => '0413-350602',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '162',
	'cdstatus' => 'N',
	'nmsearch' => 'ALMER',
	'nmclub' => 'Almere',
	'nmfull' => 'b.s.c. ALMERE \'90',
	'ftlocation' => 'Almere',
	'ftfield' => 'Fanny Blankers Koen Sportpark',
	'ftpostalcode' => '1300BB',
	'nmcity' => 'ALMERE',
	'ftphone' => '036-5326003',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '163',
	'cdstatus' => 'N',
	'nmsearch' => 'ANTIL',
	'nmclub' => 'Antillian-Stars',
	'nmfull' => 'ANTILLIAN-STARS',
	'ftlocation' => 'Utrecht',
	'ftfield' => 'Sportpark \'Welgelegen\' (BSCU)',
	'nmcity' => 'UTRECHT',
	'ftphone' => '030-2945828',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '164',
	'cdstatus' => 'N',
	'nmsearch' => 'KEYTO',
	'nmclub' => 'Keytown Hitters',
	'nmfull' => 'h.s.v. THE KEYTOWN HITTERS',
	'ftlocation' => 'Leiden',
	'ftfield' => 'Sportpark Pomona',
	'ftaddress' => 'Nachtegaallaan',
	'nmcity' => 'LEIDEN',
	'ftphone' => '071-5176709',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '165',
	'cdstatus' => 'N',
	'nmsearch' => 'FULLS',
	'nmclub' => 'Full Speed',
	'nmfull' => 'd.s.v. FULL SPEED',
	'ftlocation' => 'Delft',
	'ftaddress' => 'Kerkpolderweg 3',
	'nmcity' => 'DELFT',
	'ftphone' => '015-2618263',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '166',
	'cdstatus' => 'N',
	'nmsearch' => 'BLHIT',
	'nmclub' => 'Blue Hitters',
	'nmfull' => 'h.s.v. BLUE HITTERS',
	'ftlocation' => 'Puttershoek',
	'ftaddress' => 'Sportlaan 22b',
	'ftpostalcode' => '3299XG',
	'nmcity' => 'MAASDAM',
	'ftphone' => '078-6763746',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '167',
	'cdstatus' => 'N',
	'nmsearch' => 'KOEDI',
	'nmclub' => 'Koedijk',
	'nmfull' => 's.v. KOEDIJK',
	'ftlocation' => 'Koedijk',
	'ftaddress' => 'Saskerstraat',
	'nmcity' => 'KOEDIJK',
	'ftphone' => '072-5614900',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '168',
	'cdstatus' => 'N',
	'nmsearch' => 'BOEKA',
	'nmclub' => 'Boekaniers',
	'nmfull' => 'BOEKANIERS',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark \'Jan van Galen\'',
	'ftaddress' => 'Jan van Galenstraat',
	'nmcity' => 'AMSTERDAM',
	'ftphone' => '020-6162151',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '169',
	'cdstatus' => 'N',
	'nmsearch' => 'PANTE',
	'nmclub' => 'Panters',
	'nmfull' => 'DE PANTERS',
	'ftlocation' => 'Tiel',
	'ftfield' => 'Sportpark \'Rauwenhof\'',
	'nmcity' => 'TIEL-WEST',
	'ftphone' => '0344-621001',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '170',
	'cdstatus' => 'N',
	'nmsearch' => 'HERCU',
	'nmclub' => 'Hercules',
	'nmfull' => 'u.s.v. HERCULES',
	'ftlocation' => 'Utrecht',
	'ftfield' => 'Sportpark \'Voordorp\'',
	'ftaddress' => 'Voorveldselaan 2',
	'ftpostalcode' => '3573PV',
	'nmcity' => 'UTRECHT',
	'ftphone' => '030-2717091',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '171',
	'cdstatus' => 'N',
	'nmsearch' => 'WAPS',
	'nmclub' => 'Waps',
	'nmfull' => 'l.s.b.s.g. WAPS',
	'ftlocation' => 'Leiden',
	'ftfield' => 'Studenten Sportcentrum',
	'ftaddress' => 'Einsteinweg 6',
	'nmcity' => 'LEIDEN',
	'ftphone' => '071-5274610',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '172',
	'cdstatus' => 'N',
	'nmsearch' => 'OVERV',
	'nmclub' => 'Overveen',
	'nmfull' => 's.c. OVERVEEN',
	'ftlocation' => 'Overveen',
	'ftaddress' => 'Sportparklaan',
	'nmcity' => 'HEEMSTEDE',
	'ftphone' => '023-5286751',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '173',
	'cdstatus' => 'N',
	'nmsearch' => 'DZB',
	'nmclub' => 'DZB',
	'nmfull' => 'D.Z.B.',
	'ftlocation' => 'Rotterdam',
	'ftaddress' => 'Igor Stravinskisingel 5',
	'nmcity' => 'ROTTERDAM',
	'ftphone' => '010-4558609',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '174',
	'cdstatus' => 'N',
	'nmsearch' => 'GEMER',
	'nmclub' => 'Gemert',
	'nmfull' => 'g.h.s.v. GEMERT',
	'ftlocation' => 'Gemert',
	'ftfield' => 'Sportpark \'Molenbroek\'',
	'nmcity' => 'GEMERT',
	'ftphone' => '0492-365725',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '175',
	'cdstatus' => 'N',
	'nmsearch' => 'WINGS',
	'nmclub' => 'Wings',
	'nmfull' => 'WINGS',
	'ftlocation' => 'Den Haag',
	'ftfield' => 'Sportveld Dalton Lyceum',
	'ftaddress' => 'Laan van Meerdervoort 1770',
	'ftpostalcode' => '2555CX',
	'nmcity' => 'DEN HAAG',
	'ftphone' => '070-3238390',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '176',
	'cdstatus' => 'N',
	'nmsearch' => 'ADEG',
	'nmclub' => 'Adegeest',
	'nmfull' => 'h.s.v. ADEGEEST',
	'ftlocation' => 'Voorschoten',
	'ftaddress' => 'Admiraal de Ruytersingel',
	'nmcity' => 'VOORSCHOTEN',
	'ftphone' => '071-5720722',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '177',
	'cdstatus' => 'N',
	'nmsearch' => 'UNITE',
	'nmclub' => 'United',
	'nmfull' => 's.v. United',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Spaarne Scholengemeenschap',
	'ftaddress' => 'Zuid-Schalkwijkerweg',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5333410',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '178',
	'cdstatus' => 'N',
	'nmsearch' => 'TZB',
	'nmclub' => 'TZB',
	'nmfull' => 'T.Z.B.',
	'ftlocation' => 'Zandvoort',
	'ftfield' => 'Kennemersportpark',
	'ftaddress' => 'Kennemerweg 6',
	'ftpostalcode' => '2042XT',
	'nmcity' => 'ZANDVOORT',
	'ftphone' => '023-5714066',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '179',
	'cdstatus' => 'N',
	'nmsearch' => 'METST',
	'nmclub' => 'Met Stip',
	'nmfull' => 's.v.s.h.v. MET STIP',
	'ftlocation' => 'Delft',
	'ftfield' => 'Sportstichting Tech. Univ.',
	'ftaddress' => 'Mekelweg 8',
	'ftpostalcode' => '2628CD',
	'nmcity' => 'DELFT',
	'ftphone' => '015-2782443',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '180',
	'cdstatus' => 'N',
	'nmsearch' => 'TIWSU',
	'nmclub' => 'TIW-Survivors',
	'nmfull' => 'TIW-SURVIVORS',
	'ftlocation' => 'Diemen',
	'ftfield' => 'Sportpark \'De Diemen\'',
	'ftaddress' => 'Sportlaan 9',
	'ftpostalcode' => '1111PC',
	'nmcity' => 'DIEMEN',
	'ftphone' => '020-6002747',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '181',
	'cdstatus' => 'N',
	'nmsearch' => 'HARRI',
	'nmclub' => 'Harriers',
	'nmfull' => 'h.s.v. THE HARRIERS',
	'ftlocation' => 'Zeewolde',
	'ftfield' => 'Sportpark \'De Horst\'',
	'nmcity' => 'ZEEWOLDE',
	'ftphone' => '036-5224725',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '182',
	'cdstatus' => 'N',
	'nmsearch' => 'WIZAR',
	'nmclub' => 'Wizards of Boz',
	'nmfull' => 'WIZARDS OF BOZ',
	'ftlocation' => 'Bergen op Zoom',
	'ftfield' => '\'Kijk in \'t Pot\'',
	'ftaddress' => 'Zuid-Westsingel',
	'ftpostalcode' => '4611KH',
	'nmcity' => 'BERGEN OP ZOOM',
	'ftphone' => '0164-245618',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '183',
	'cdstatus' => 'N',
	'nmsearch' => 'HIGHT',
	'nmclub' => 'HighTechHitters',
	'nmfull' => 'h.s.v. HIGH-TECH-HITTERS',
	'ftlocation' => 'Enschede',
	'ftfield' => 'Sportcentrum Univ. Twente',
	'ftpostalcode' => '7500AE',
	'nmcity' => 'ENSCHEDE',
	'ftphone' => '053-4898001',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '184',
	'cdstatus' => 'N',
	'nmsearch' => 'SOA',
	'nmclub' => 'SOA',
	'nmfull' => 'S.O.A.',
	'ftlocation' => 'Den Haag',
	'ftaddress' => 'Machiel Vrijenhoeklaan',
	'nmcity' => 'DEN HAAG',
	'ftphone' => '070-3250113',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '185',
	'cdstatus' => 'N',
	'nmsearch' => 'KEYST',
	'nmclub' => 'Keyst. Stealers',
	'nmfull' => 'h.s.v.b. KEYSTONE STEALERS',
	'ftlocation' => 'Boxmeer',
	'nmcity' => 'BOXMEER',
	'ftphone' => '0485-571404',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '186',
	'cdstatus' => 'N',
	'nmsearch' => 'NEDLL',
	'nmclub' => 'Nedlloyd\'70',
	'nmfull' => 'NEDLLOYD \'70',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark IJsbaanpad',
	'ftaddress' => 'IJsbaanpad',
	'nmcity' => 'AMSTERDAM',
	'ftphone' => '020-6794226',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '187',
	'cdstatus' => 'N',
	'nmsearch' => 'ZWOLL',
	'nmclub' => 'Zwolle',
	'nmfull' => 's.v. ZWOLLE',
	'ftlocation' => 'Zwolle',
	'ftfield' => 'Sportpark \'De Marslanden\'',
	'ftaddress' => 'Hyacintstraat 66',
	'ftpostalcode' => '8013XZ',
	'nmcity' => 'ZWOLLE',
	'ftphone' => '038-4211082',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '188',
	'cdstatus' => 'N',
	'nmsearch' => 'OGSB',
	'nmclub' => 'Onze Gezellen',
	'nmfull' => 'r.k.s.v. ONZE GEZELLEN',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Sportpark Vlietweg',
	'ftaddress' => 'Vlietweg',
	'ftpostalcode' => '2026BZ',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5373967',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '189',
	'cdstatus' => 'N',
	'nmsearch' => 'DSSSB',
	'nmclub' => 'DSS',
	'nmfull' => 'r.k.s.v. D.S.S.',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Kleverlaan',
	'ftaddress' => 'Kleverlaan',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5270272',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '190',
	'cdstatus' => 'N',
	'nmsearch' => 'TERSB',
	'nmclub' => 'Terrasvogels',
	'nmfull' => 'TERRASVOGELS',
	'ftlocation' => 'Santpoort',
	'ftfield' => 'Sportpark \"De Elta\"',
	'ftpostalcode' => '2082XM',
	'nmcity' => 'SANTPOORT',
	'ftphone' => '023-5378652',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '191',
	'cdstatus' => 'N',
	'nmsearch' => 'KINHS',
	'nmclub' => 'Kinheim SB',
	'nmfull' => 's.c. KINHEIM',
	'ftlocation' => 'Haarlem',
	'ftfield' => 'Gem. Sportpark Badmintonpad',
	'ftaddress' => 'Badmintonpad',
	'ftpostalcode' => '2023BT',
	'nmcity' => 'HAARLEM',
	'ftphone' => '023-5260021',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '192',
	'cdstatus' => 'N',
	'nmsearch' => 'KNBSB',
	'nmclub' => 'K.N.B.S.B.',
	'nmfull' => 'Kon.Ned.Base- & Softball Bond',
	'ftlocation' => 'Santpoort-Noord',
	'ftaddress' => 'Burg. Weertsplantsoen 112',
	'ftpostalcode' => '2071PK',
	'nmcity' => 'SANTPOORT-NOORD',
	'ftphone' => '023-5390244',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '193',
	'cdstatus' => 'N',
	'nmsearch' => 'AMIGO',
	'nmclub' => 'Amigo',
	'nmfull' => 'b.s.c. AMIGO',
	'ftlocation' => 'Groesbeek',
	'ftfield' => 'Sportpark Zuid',
	'ftaddress' => 'Nijerf',
	'nmcity' => 'GROESBEEK',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '194',
	'cdstatus' => 'N',
	'nmsearch' => 'ATLAN',
	'nmclub' => 'Atlanta Stars',
	'nmfull' => 'ATLANTA STARS',
	'ftlocation' => 'Rotterdam',
	'ftfield' => 'Sportpark Prinsenlaan',
	'nmcity' => 'ROTTERDAM',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '195',
	'cdstatus' => 'N',
	'nmsearch' => 'BIENT',
	'nmclub' => 'Biento',
	'nmfull' => 's.s.m. BIENTO',
	'ftlocation' => 'Leiden',
	'nmcity' => 'LEIDEN',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '196',
	'cdstatus' => 'N',
	'nmsearch' => 'ATC',
	'nmclub' => 'ATC \'65',
	'nmfull' => 'A.T.C. \'65',
	'ftlocation' => 'Hengelo',
	'ftfield' => 'Sportcomplex stadion Veldwijk',
	'ftaddress' => 'Pruisische Veldweg',
	'nmcity' => 'HENGELO',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '197',
	'cdstatus' => 'N',
	'nmsearch' => 'BATTE',
	'nmclub' => 'Batters',
	'nmfull' => 'h.s.v. BATTERS',
	'ftlocation' => 'Putte',
	'ftfield' => 'Sportpark \'De Boshoek\'',
	'ftaddress' => 'Herenbaan',
	'nmcity' => 'PUTTE',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '198',
	'cdstatus' => 'N',
	'nmsearch' => 'BLWIN',
	'nmclub' => 'Black Wings',
	'nmfull' => 'BLACK WINGS',
	'ftlocation' => 'Deurne',
	'ftfield' => 'Sportpark \'Kranenmortel\'',
	'nmcity' => 'DEURNE',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '199',
	'cdstatus' => 'N',
	'nmsearch' => 'CRACK',
	'nmclub' => 'Cracks',
	'nmfull' => 'DE CRACKS',
	'ftlocation' => 'Roermond',
	'ftfield' => 'Sportpark \'De Wijker 2\'',
	'ftaddress' => 'Jagerstraat',
	'nmcity' => 'ROERMOND',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '200',
	'cdstatus' => 'N',
	'nmsearch' => 'CHEET',
	'nmclub' => 'Cheetahs',
	'nmfull' => 'h.s.v. Cheetahs',
	'ftlocation' => 'Beek',
	'ftfield' => 'Proosdij-Noord',
	'ftpostalcode' => '6191NA',
	'nmcity' => 'BEEK',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '201',
	'cdstatus' => 'N',
	'nmsearch' => 'GRHEA',
	'nmclub' => 'Green Hearts',
	'nmfull' => 'GREEN HEARTS',
	'ftlocation' => 'Montfoort',
	'ftfield' => 'Sportpark \'Rapijnen\'',
	'ftaddress' => 'De Beide Vlooswijkenlaan 1',
	'ftpostalcode' => '3461GB',
	'nmcity' => 'LINSCHOTEN',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '202',
	'cdstatus' => 'N',
	'nmsearch' => 'ISLAN',
	'nmclub' => 'Islanders',
	'nmfull' => 'h.s.v. THE ISLANDERS',
	'ftlocation' => 'Oude Tonge',
	'ftaddress' => 'Van Halenstraat',
	'ftpostalcode' => '3255BE',
	'nmcity' => 'OUDE TONGE',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '203',
	'cdstatus' => 'N',
	'nmsearch' => 'KNICK',
	'nmclub' => 'Knickerbockers',
	'nmfull' => 'DE KNICKERBOCKERS',
	'ftlocation' => 'Soest',
	'ftaddress' => 'Koningsweg',
	'nmcity' => 'SOEST',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '204',
	'cdstatus' => 'N',
	'nmsearch' => 'MATCH',
	'nmclub' => 'Matchmakers',
	'nmfull' => 'h.s.c. MATCHMAKERS',
	'ftlocation' => 'Wageningen',
	'ftfield' => 'Sportpark \'De Zoom\'',
	'ftaddress' => 'Zoomweg',
	'ftpostalcode' => '6705DM',
	'nmcity' => 'WAGENINGEN',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '205',
	'cdstatus' => 'N',
	'nmsearch' => 'QUICK',
	'nmclub' => 'Quick',
	'nmfull' => 'a.h.c. QUICK',
	'ftlocation' => 'Amsterdam',
	'ftfield' => 'Sportpark \'Sloten\'',
	'ftaddress' => 'Sloterweg 1045',
	'nmcity' => 'AMSTERDAM',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '206',
	'cdstatus' => 'N',
	'nmsearch' => 'REDGE',
	'nmclub' => 'Red Geese',
	'nmfull' => 'THE RED GEESE',
	'ftlocation' => 'Goes',
	'ftfield' => 'Sportterrein \'Het Schenge\'',
	'nmcity' => 'GOES',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '207',
	'cdstatus' => 'N',
	'nmsearch' => 'SAMAC',
	'nmclub' => 'Samacols',
	'nmfull' => 'h.s.c. SAMACOLS',
	'ftlocation' => 'Kerkrade',
	'ftpostalcode' => '6372XA',
	'nmcity' => 'KERKRADE',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '208',
	'cdstatus' => 'N',
	'nmsearch' => 'SULLI',
	'nmclub' => 'Sullivan\'s',
	'nmfull' => 'SULLIVAN\'S GREEN DEVILS',
	'ftlocation' => 'Monnickendam',
	'ftfield' => 'Sportpark \'Markgouw\'',
	'nmcity' => 'MONNICKENDAM',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '209',
	'cdstatus' => 'N',
	'nmsearch' => 'UITSM',
	'nmclub' => 'Uitsmijters\'55',
	'nmfull' => 'UITSMIJTERS\'55',
	'ftlocation' => 'Almelo',
	'ftfield' => '\'\'t Maatveld-Nijreesbos\'',
	'ftpostalcode' => '7627PB',
	'nmcity' => 'ALMELO',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '210',
	'cdstatus' => 'N',
	'nmsearch' => 'MUSTA',
	'nmclub' => 'Mustangs',
	'nmfull' => 'h.s.c.v. MUSTANGS',
	'ftlocation' => 'Venlo',
	'ftfield' => 'Sportpark \'Herungerberg\'',
	'nmcity' => 'VENLO',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '211',
	'cdstatus' => 'N',
	'nmsearch' => 'ALLST',
	'nmclub' => 'All Stars',
	'nmfull' => 'ALL STARS',
	'ftlocation' => 'Heerlan',
	'ftfield' => 'Sportpark \'De Varenbreuk\'',
	'nmcity' => 'HEERLEN',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '212',
	'cdstatus' => 'N',
	'nmsearch' => 'MEPPE',
	'nmclub' => 'Meppers',
	'nmfull' => 'MEPPERS EERSEL',
	'ftlocation' => 'Eersel',
	'ftfield' => 'Sportpark Postelseweg',
	'ftaddress' => 'Postelseweg',
	'ftpostalcode' => '5520AC',
	'nmcity' => 'EERSEL',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '213',
	'cdstatus' => 'N',
	'nmsearch' => 'INDIA',
	'nmclub' => 'Indians',
	'nmfull' => 'h.s.v. INDIANS',
	'ftlocation' => 'Weert',
	'ftfield' => 'Sportpark \'Boshoven\'',
	'ftaddress' => 'Vrakkerveld 7',
	'ftpostalcode' => '6002AZ',
	'nmcity' => 'WEERT',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '214',
	'cdstatus' => 'N',
	'nmsearch' => 'BOOST',
	'nmclub' => 'Boosters',
	'nmfull' => 'BOOSTERS',
	'ftlocation' => 'Roosendaal',
	'ftfield' => 'Sportpark \'Vierhoven\'',
	'ftaddress' => 'Nisepenseweg 1',
	'ftpostalcode' => '4707RA',
	'nmcity' => 'ROOSENDAAL',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '215',
	'cdstatus' => 'N',
	'nmsearch' => 'METS',
	'nmclub' => 'Mets',
	'nmfull' => 's.h.s.v. METS',
	'ftlocation' => 'Schoonhoven',
	'ftfield' => 'Sportvelden Oost',
	'ftaddress' => 'Meidoornpad',
	'nmcity' => 'SCHOONHOVEN',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '216',
	'cdstatus' => 'N',
	'nmsearch' => 'MACHO',
	'nmclub' => 'Machos',
	'nmfull' => 'd.s.b.s.c. MACHOS',
	'ftlocation' => 'Delft',
	'ftfield' => 'Sportcentrum Mekelweg',
	'ftaddress' => 'Mekelweg 8',
	'ftpostalcode' => '2628CD',
	'nmcity' => 'DELFT',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '217',
	'cdstatus' => 'N',
	'nmsearch' => 'BLFRE',
	'nmclub' => 'Blue Frets',
	'nmfull' => 'BLUE FRETS',
	'ftlocation' => 'Harlingen',
	'ftfield' => 'Naast Sporthal Waddenhal',
	'nmcity' => 'HARLINGEN',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '218',
	'cdstatus' => 'N',
	'nmsearch' => 'WHITE',
	'nmclub' => 'White Cats',
	'nmfull' => 'WHITE CATS',
	'ftlocation' => 'Sneek',
	'ftfield' => '\'Noorderhoek\' Hubert Sneek v.4',
	'ftaddress' => 'Schotanusstraat',
	'nmcity' => 'SNEEK',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '219',
	'cdstatus' => 'N',
	'nmsearch' => 'UDEN',
	'nmclub' => 'Uden Red-Sox',
	'nmfull' => 'h.s.v. UDEN RED-SOX',
	'ftlocation' => 'Uden',
	'ftfield' => 'Sportpark \'Moleneind\'',
	'ftaddress' => 'Aalstweg',
	'nmcity' => 'UDEN',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '220',
	'cdstatus' => 'N',
	'nmsearch' => 'KNIGH',
	'nmclub' => 'Knights',
	'nmfull' => 'b.s.c. KNIGHTS',
	'ftlocation' => 'Leek',
	'ftfield' => 'Sportpark \'Rodenburg\'',
	'nmcity' => 'LEEK',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '221',
	'cdstatus' => 'N',
	'nmsearch' => 'TRIDENTS',
	'nmclub' => 'Tridents',
	'nmfull' => 'Levi',
	'ftlocation' => 'Rotterdam',
	'nmcity' => 'ROTTERDAM',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '222',
	'cdstatus' => 'N',
	'nmsearch' => 'GIANTS',
	'nmclub' => 'Giants',
	'ftlocation' => 'Diemen',
	'nmcity' => 'DIEMEN',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '223',
	'cdstatus' => 'N',
	'nmsearch' => 'TIJGERS',
	'nmclub' => 'Amstel Tijgers',
	'ftlocation' => 'Amsterdam',
	'nmcity' => 'AMSTERDAM',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '224',
	'cdstatus' => 'N',
	'nmsearch' => 'HHC',
	'nmclub' => 'HHC',
	'nmfull' => 'Haarlemse Honkbal Club',
	'ftlocation' => 'Haarlem',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '225',
	'cdstatus' => 'N',
	'nmsearch' => 'CTC',
	'nmclub' => 'CTC',
	'nmfull' => 'CTC',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '226',
	'cdstatus' => 'N',
	'nmsearch' => 'HC38',
	'nmclub' => 'HC \'38',
	'nmfull' => 'Honkbalclub 38',
	'ftlocation' => 'Bussum',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '227',
	'cdstatus' => 'N',
	'nmsearch' => 'AJAX',
	'nmclub' => 'Ajax',
	'nmfull' => 'Ajax',
	'ftlocation' => 'Amsterdam',
	'ftphone' => '020',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '228',
	'cdstatus' => 'N',
	'nmsearch' => 'HVA',
	'nmclub' => 'HVA',
	'nmfull' => 'HVA',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '229',
	'cdstatus' => 'N',
	'nmsearch' => 'VVGA',
	'nmclub' => 'VVGA',
	'nmfull' => 'VVGA',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '230',
	'cdstatus' => 'N',
	'nmsearch' => 'HCK',
	'nmclub' => 'H.C.K.',
	'nmfull' => 'HCK',
	'ftlocation' => 'Haarlem',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '231',
	'cdstatus' => 'N',
	'nmsearch' => 'MINISTERPA',
	'nmclub' => 'Ministerpark',
	'ftlocation' => 'Naarden',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '232',
	'cdstatus' => 'N',
	'nmsearch' => 'CHEFANA',
	'nmclub' => 'CHEFANA',
	'nmfull' => 'Chemische Fabriek Naarden',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '233',
	'cdstatus' => 'A',
	'nmsearch' => 'Scimitars',
	'nmclub' => 'Scimitars',
	'nmfull' => 'Scimitars',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '234',
	'cdstatus' => 'A',
	'nmsearch' => 'OLYMP',
	'nmclub' => 'Olympia Haarlem',
	'nmfull' => 'FysioExpert Olympia Haarlem',
	'ftlocation' => 'Jan Gijzenkade 213',
	'ftpostalcode' => '2025MA',
	'nmcity' => 'HAARLEM',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '235',
	'cdstatus' => 'A',
	'nmsearch' => 'SPIKES',
	'nmclub' => 'SPIKES',
	'nmfull' => 'h.s.v. Spikes',
	'ftfield' => 'Sportpark Sportpolder',
	'ftaddress' => 'Sportpolderweg 11',
	'ftpostalcode' => '3205LZ',
	'nmcity' => 'SPIJKENISSE',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '236',
	'cdstatus' => 'A',
	'nmsearch' => 'DIAMO',
	'nmclub' => 'Nieuwegein Diamonds',
	'nmfull' => 'Nieuwegein Diamonds',
	'ftfield' => 'Sportpark Galecopperzoom',
	'ftaddress' => 'Sportpark Galecop 2',
	'ftpostalcode' => '3438HX',
	'nmcity' => 'NIEUWEGEIN',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '237',
	'cdstatus' => 'A',
	'nmsearch' => 'GRYPH',
	'nmclub' => 'Gryphons',
	'nmfull' => 'Gryphons',
	'ftfield' => 'Sportpark De Groote Wielen',
	'ftaddress' => 'Groote Vlietlaan 61',
	'ftpostalcode' => '5245PB',
	'nmcity' => 'ROSMALEN',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idclub' => '238',
	'cdstatus' => 'A',
	'nmsearch' => 'CENTRALS',
	'nmclub' => 'Centrals',
	'nmfull' => 'Centrals',
	'ftfield' => 'Sportpark Weltevreden',
	'ftaddress' => 'Voordorpsedijk 73',
	'ftpostalcode' => '3737BM',
	'nmcity' => 'GROENEKAN',
	'created_at' => '2019-03-24 09:16:25',
	'updated_by' => 'info@honkbalmuseum.nl',
],


    	];

        $table = $this->table('clubs');
        $table->insert($data)
              ->save();

    }
}
