<?php


use Phinx\Seed\AbstractSeed;

class SourcesSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
    	$data = [
[
	'idsource' => '1',
	'nmsearch' => 'VONK',
	'nmsource' => 'Fotostudio Vonk',
	'nmcontact' => 'Hr Vonk',
	'nmaddress' => 'Brinklaan 22/B',
	'nmpostal' => '1404ET',
	'nmcity' => 'Bussum',
	'ftphone' => '035-6916165',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '2',
	'nmsearch' => 'GOOI',
	'nmsource' => 'Dagblad de Gooi- en Eemlander',
	'ftwebsite' => 'www.gooieneemlander.nl',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '3',
	'nmsearch' => 'MUSEUM',
	'nmsource' => 'Nederlands Honkbalmuseum',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '4',
	'nmsearch' => 'KASTERMANS',
	'nmsource' => 'Ton Kastermans',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '5',
	'nmsearch' => 'AD',
	'nmsource' => 'Algemeen Dagblad',
	'ftwebsite' => 'www.ad.nl',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '6',
	'nmsearch' => 'TELEGRAAF',
	'nmsource' => 'De Telegraaf',
	'ftwebsite' => 'www.telegraaf.nl',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '7',
	'nmsearch' => 'VOLKSKRANT',
	'nmsource' => 'De Volkskrant',
	'ftwebsite' => 'www.volkskrant.nl',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '8',
	'nmsearch' => 'PAROOL',
	'nmsource' => 'Het Parool',
	'ftwebsite' => 'www.parool.nl',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '9',
	'nmsearch' => 'ONBEKEND',
	'nmsource' => 'ONBEKEND',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '10',
	'nmsearch' => 'NRC',
	'nmsource' => 'NRC Handelsblad',
	'ftwebsite' => 'www.nrc-handelsblad.n',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '11',
	'nmsearch' => 'ANP',
	'nmsource' => 'Algemeen Nederlands Persburo',
	'ftwebsite' => 'www.anp.nl',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '12',
	'nmsearch' => 'HAARLEMS',
	'nmsource' => 'Haarlems Dagblad',
	'ftwebsite' => 'www.haarlemsdagblad.nl',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '13',
	'nmsearch' => 'MOERMAN',
	'nmsource' => 'Gijs Moerman',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '14',
	'nmsearch' => 'ROTTERDAM',
	'nmsource' => 'Rotterdams Dagblad',
	'ftwebsite' => 'www.rotterdamsdagblad.nl',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '15',
	'nmsearch' => 'GOOIS',
	'nmsource' => 'Goois Weekblad',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '16',
	'nmsearch' => 'EEMBODE',
	'nmsource' => 'Gooi en Eembode',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '17',
	'nmsearch' => 'TELESPORT',
	'nmsource' => 'Telesport',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '19',
	'nmsearch' => 'COURANT',
	'nmsource' => 'De Bussumsche Courant',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '20',
	'nmsearch' => 'EINDHOVEN',
	'nmsource' => 'Eindhovens Dagblad',
	'ftwebsite' => 'www.eindhovensdagblad.nl',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
],
[
	'idsource' => '22',
	'nmsearch' => 'NIEUWSBLAD',
	'nmsource' => 'Goois Nieuwsblad',
	'cdpermission' => 'J',
	'dtlastmut' => '2005-12-18',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '2005-12-18',
],
[
	'idsource' => '23',
	'nmsearch' => 'VV',
	'nmsource' => 'Het Vrije Volk',
	'cdpermission' => 'J',
	'dtlastmut' => '2005-12-18',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '25',
	'nmsearch' => 'HAAGSE',
	'nmsource' => 'Haagse Courant',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-01-03',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '26',
	'nmsearch' => 'TROUW',
	'nmsource' => 'Trouw',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-01-04',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '27',
	'nmsearch' => 'Kok',
	'nmsource' => 'Kok',
	'nmaddress' => 'Emmastraat 34',
	'nmcity' => 'Hilversum',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-01-13',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '2006-01-13',
],
[
	'idsource' => '28',
	'nmsearch' => 'AMERSFOORT',
	'nmsource' => 'Amersfoortse Courant',
	'ftwebsite' => 'http://www.amersfoortsecourant.nl/',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-01-13',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '2006-01-13',
],
[
	'idsource' => '29',
	'nmsearch' => 'NIEUWS',
	'nmsource' => 'Nieuws van de Dag',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-01-14',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '30',
	'nmsearch' => 'UTRECHT',
	'nmsource' => 'Utrechts Nieuwsblad',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-01-14',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '2006-01-14',
],
[
	'idsource' => '31',
	'nmsearch' => 'COP',
	'nmsource' => 'Alfred Cop Fotografie',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-01-14',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '32',
	'nmsearch' => 'FOPPE',
	'nmsource' => 'United Photo\'s Foppe de Boer',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-01-15',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '33',
	'nmsearch' => 'RAPIDS',
	'nmsource' => 'The Grand Rapids Press',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-01-19',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '34',
	'nmsearch' => 'HCAW',
	'nmsource' => 'HCAW Archief',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-01-24',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '35',
	'nmsearch' => 'PLAY',
	'nmsource' => 'Play Off',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-11-06',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '36',
	'nmsearch' => 'STEVENS',
	'nmsource' => 'Stevens',
	'nmcontact' => 'Stevens',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-12-18',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '37',
	'nmsearch' => 'FRIEDLANDE',
	'nmsource' => 'FriedlÃ¤nder',
	'nmcontact' => 'FriedlÃ¤nder',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-12-20',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '38',
	'nmsearch' => 'EBERHARD',
	'nmsource' => 'Eberhard',
	'nmcontact' => 'Eberhard',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-12-24',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '39',
	'nmsearch' => 'AP',
	'nmsource' => 'Associated Press',
	'cdpermission' => 'J',
	'dtlastmut' => '2006-12-29',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '40',
	'nmsearch' => 'ANEFO',
	'nmsource' => 'ANEFO',
	'cdpermission' => 'J',
	'dtlastmut' => '2007-01-19',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '41',
	'nmsearch' => 'GPD',
	'nmsource' => 'Geassocieerde Pers Diensten',
	'ftwebsite' => 'www.gpd.nl',
	'cdpermission' => 'J',
	'dtlastmut' => '0000-00-00',
],
[
	'idsource' => '42',
	'nmsearch' => 'EPA',
	'nmsource' => 'European Press Agency',
	'cdpermission' => 'J',
	'dtlastmut' => '2007-08-13',
	'nmlastmut' => 'dennis.vorst@wanadoo.nl',
	'dtprevmut' => '0000-00-00',
],
[
	'idsource' => '43',
	'nmsearch' => 'BUSSUMS',
	'nmsource' => 'Bussums Nieuws',
	'cdpermission' => 'N',
	'dtlastmut' => '0000-00-00',
	'nmlastmut' => 'administrator',
],
[
	'idsource' => '44',
	'nmsearch' => 'ALMERE',
	'nmsource' => 'Almere Vandaag',
	'cdpermission' => 'N',
	'dtlastmut' => '0000-00-00',
],
[
	'idsource' => '45',
	'nmsearch' => 'BUSSUMSE',
	'nmsource' => 'Bussumse Krant',
	'cdpermission' => 'N',
	'dtlastmut' => '0000-00-00',
],
[
	'idsource' => '46',
	'nmsearch' => 'GOOISE',
	'nmsource' => 'Gooise Leven',
	'cdpermission' => 'N',
	'dtlastmut' => '0000-00-00',
],
[
	'idsource' => '47',
	'nmsearch' => 'METROPOOL',
	'nmsource' => 'Metropool Sport',
	'cdpermission' => 'N',
	'dtlastmut' => '0000-00-00',
],
[
	'idsource' => '48',
	'nmsearch' => 'SPITS',
	'nmsource' => 'Spits',
	'cdpermission' => 'N',
	'dtlastmut' => '0000-00-00',
],
[
	'idsource' => '49',
	'nmsearch' => 'NAARDER',
	'nmsource' => 'Naarder Koerier',
	'cdpermission' => 'N',
	'dtlastmut' => '0000-00-00',
],

    	];

        $table = $this->table('sources');
        $table->insert($data)
              ->save();

    }
}
