<?php


use Phinx\Seed\AbstractSeed;

class TeamsSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
    	$data = [

[
	'idteam' => '1',
	'idclub' => '1',
	'nmteam' => 'A.B.C.',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '2',
	'idclub' => '2',
	'nmteam' => 'ADO',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '3',
	'idclub' => '2',
	'nmteam' => 'AdoLakers',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '4',
	'idclub' => '2',
	'nmteam' => 'Hypotheekzeker.nl Tornado\'s',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '5',
	'idclub' => '2',
	'nmteam' => 'Install Data ADO',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '6',
	'idclub' => '10',
	'nmteam' => 'D.I.O.',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '7',
	'idclub' => '32',
	'nmteam' => 'DSS',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '8',
	'idclub' => '45',
	'nmteam' => 'Feijenoord',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '9',
	'idclub' => '45',
	'nmteam' => 'Sparta/Feijenoord',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '10',
	'idclub' => '54',
	'nmteam' => 'S.C. Haarlem',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '11',
	'idclub' => '55',
	'nmteam' => 'Kinzo Nicols',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '12',
	'idclub' => '55',
	'nmteam' => 'Nicols',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '13',
	'idclub' => '55',
	'nmteam' => 'Tetramin Nicols',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '14',
	'idclub' => '56',
	'nmteam' => 'Mampaey Hawks',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '15',
	'idclub' => '56',
	'nmteam' => 'Mampaey The Hawks',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '16',
	'idclub' => '56',
	'nmteam' => 'The Hawks',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '17',
	'idclub' => '59',
	'nmteam' => 'H.C.A.W.',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '18',
	'idclub' => '59',
	'nmteam' => 'HCAW Bussum',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '19',
	'idclub' => '59',
	'nmteam' => 'Mr.Cocker HCAW',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '20',
	'idclub' => '59',
	'nmteam' => 'Mr.Cocker HCAW/Tijgers',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '21',
	'idclub' => '59',
	'nmteam' => 'Nikon HCAW',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '22',
	'idclub' => '67',
	'nmteam' => 'Konica Minolta Pioniers',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '23',
	'idclub' => '67',
	'nmteam' => 'Minolta Pioniers',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '24',
	'idclub' => '67',
	'nmteam' => 'Vaessen Pioniers',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '25',
	'idclub' => '72',
	'nmteam' => 'Corendon Kinheim',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '26',
	'idclub' => '72',
	'nmteam' => 'DPA Kinheim',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '27',
	'idclub' => '72',
	'nmteam' => 'Planeta Kinheim',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '28',
	'idclub' => '72',
	'nmteam' => 'Vax Kinheim',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '29',
	'idclub' => '72',
	'nmteam' => 'Vrienden/Kinheim',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '30',
	'idclub' => '85',
	'nmteam' => 'Curacao Neptunus',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '31',
	'idclub' => '85',
	'nmteam' => 'DOOR Neptunus',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '32',
	'idclub' => '85',
	'nmteam' => 'Kok Neptunus',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '33',
	'idclub' => '85',
	'nmteam' => 'Levi\'s Neptunus',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '34',
	'idclub' => '85',
	'nmteam' => 'Tropicana Neptununs',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '35',
	'idclub' => '91',
	'nmteam' => 'O.V.V.O.',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '36',
	'idclub' => '98',
	'nmteam' => 'Amsterdam Pirates',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '37',
	'idclub' => '98',
	'nmteam' => 'L&D Amsterdam',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '38',
	'idclub' => '98',
	'nmteam' => 'L&D Amsterdam P.',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '39',
	'idclub' => '98',
	'nmteam' => 'Tas Detach Pirates',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '40',
	'idclub' => '99',
	'nmteam' => 'P.S.V.',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '41',
	'idclub' => '100',
	'nmteam' => 'Freshup Quick',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '42',
	'idclub' => '100',
	'nmteam' => 'Landis Quick',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '43',
	'idclub' => '100',
	'nmteam' => 'Smit & Dorlas Quick',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '44',
	'idclub' => '108',
	'nmteam' => 'Rooswijk',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '45',
	'idclub' => '112',
	'nmteam' => 'Schoten',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '46',
	'idclub' => '119',
	'nmteam' => 'Sparta',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '47',
	'idclub' => '119',
	'nmteam' => 'Vector Sparta',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '48',
	'idclub' => '119',
	'nmteam' => 'Vitrine Art SParta',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '49',
	'idclub' => '121',
	'nmteam' => 'Rijnhaave de Spartaan',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '50',
	'idclub' => '124',
	'nmteam' => 'Storks',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '51',
	'idclub' => '131',
	'nmteam' => 'Gambro Twins',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '52',
	'idclub' => '131',
	'nmteam' => 'Twins',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '53',
	'idclub' => '135',
	'nmteam' => 'Ola UVV',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '54',
	'idclub' => '135',
	'nmteam' => 'U.V.V.',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '55',
	'idclub' => '135',
	'nmteam' => 'UVV',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '56',
	'idclub' => '141',
	'nmteam' => 'Volewijckers',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '57',
	'idclub' => '162',
	'nmteam' => 'Instant Holland Almere',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '58',
	'idclub' => '162',
	'nmteam' => 'Ubink en Co Almere',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '59',
	'idclub' => '180',
	'nmteam' => 'H.C.T.I.W.',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '60',
	'idclub' => '222',
	'nmteam' => 'Unique Giants',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '61',
	'idclub' => '223',
	'nmteam' => 'Amstel Tijgers',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '62',
	'idclub' => '224',
	'nmteam' => 'H.H.C.',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '63',
	'idclub' => '225',
	'nmteam' => 'C.T.C.',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '64',
	'idclub' => '227',
	'nmteam' => 'Ajax',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '65',
	'idclub' => '228',
	'nmteam' => 'H.V.A.',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '66',
	'idclub' => '229',
	'nmteam' => 'V.V.G.A.',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '67',
	'idclub' => '230',
	'nmteam' => 'H.C.K.',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '68',
	'idclub' => '72',
	'nmteam' => 'Kinheim',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '69',
	'idclub' => '98',
	'nmteam' => 'L&D Amsterdam Pirates',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '70',
	'idclub' => '126',
	'nmteam' => 'Terrasvogels',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '71',
	'idclub' => '32',
	'nmteam' => 'DSS',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '72',
	'idclub' => '135',
	'nmteam' => 'Pickles UVV',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '73',
	'idclub' => '131',
	'nmteam' => 'De Glaskoning Twins',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '74',
	'idclub' => '59',
	'nmteam' => 'HCAW',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '75',
	'idclub' => '60',
	'nmteam' => 'Double Stars Heiloo H1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '76',
	'idclub' => '84',
	'nmteam' => 'Orioles H1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '77',
	'idclub' => '90',
	'nmteam' => 'Onze Gezellen H1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '78',
	'idclub' => '124',
	'nmteam' => 'Storks H1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '79',
	'idclub' => '118',
	'nmteam' => 'Sparks Haarlem H1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '80',
	'idclub' => '101',
	'nmteam' => 'RCH-Pinguins H1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '81',
	'idclub' => '56',
	'nmteam' => 'The Hawks H1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '82',
	'idclub' => '100',
	'nmteam' => 'Quick Amersfoort H1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '83',
	'idclub' => '41',
	'nmteam' => 'Euro Stars H1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '84',
	'idclub' => '85',
	'nmteam' => 'CuraÃ§ao Tridents RH1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '85',
	'idclub' => '67',
	'nmteam' => 'Omron Pioniers RH1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '86',
	'idclub' => '98',
	'nmteam' => 'Amsterdam Pirates RH1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '87',
	'idclub' => '59',
	'nmteam' => 'HCAW RH1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '88',
	'idclub' => '32',
	'nmteam' => 'DSS RH1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '89',
	'idclub' => '72',
	'nmteam' => 'Kinheim RH1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '90',
	'idclub' => '131',
	'nmteam' => 'De Glaskoning Twins RH1',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '91',
	'idclub' => '192',
	'nmteam' => 'Talent Team Holland',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '92',
	'idclub' => '131',
	'nmteam' => 'De Glaskoning Twins',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '93',
	'idclub' => '234',
	'nmteam' => 'FysioExpert Olympia Haarlem',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '94',
	'idclub' => '127',
	'nmteam' => 'Tex Town Tigers',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '95',
	'idclub' => '118',
	'nmteam' => 'Oolders Omaco Sparks Haarlem',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '96',
	'idclub' => '100',
	'nmteam' => 'Quick Amersfoort HS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '97',
	'idclub' => '67',
	'nmteam' => 'Hoofddorp Pioniers HS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '98',
	'idclub' => '235',
	'nmteam' => 'Spikes HS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '99',
	'idclub' => '3',
	'nmteam' => 'Alcmaria Victrix HS2',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '100',
	'idclub' => '128',
	'nmteam' => 'Thamen HS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '101',
	'idclub' => '236',
	'nmteam' => 'Nieuwegein Diamonds HS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '102',
	'idclub' => '34',
	'nmteam' => 'DVH HS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '103',
	'idclub' => '149',
	'nmteam' => 'Zuidvogels HS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '104',
	'idclub' => '162',
	'nmteam' => 'Almere \'90 HS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '105',
	'idclub' => '68',
	'nmteam' => 'Hygiea HS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '106',
	'idclub' => '176',
	'nmteam' => 'Adegeest HS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '107',
	'idclub' => '124',
	'nmteam' => 'Storks HS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '108',
	'idclub' => '24',
	'nmteam' => 'Catch HS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '109',
	'idclub' => '135',
	'nmteam' => 'UVV DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '110',
	'idclub' => '107',
	'nmteam' => 'ROEF! DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '111',
	'idclub' => '41',
	'nmteam' => 'BA Euro Stars DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '112',
	'idclub' => '67',
	'nmteam' => 'Hoofddorp Pioniers DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '113',
	'idclub' => '5',
	'nmteam' => 'Ban-Topa Future Stars DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '114',
	'idclub' => '3',
	'nmteam' => 'Alcmaria Victrix DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '115',
	'idclub' => '90',
	'nmteam' => 'Onze Gezellen DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '116',
	'idclub' => '237',
	'nmteam' => 'Gryphons DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '117',
	'idclub' => '23',
	'nmteam' => 'Caribe DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '118',
	'idclub' => '85',
	'nmteam' => 'Neptunus DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '119',
	'idclub' => '98',
	'nmteam' => 'Amsterdam Pirates DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '120',
	'idclub' => '59',
	'nmteam' => 'HCAW DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '121',
	'idclub' => '11',
	'nmteam' => 'BA Birds DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '122',
	'idclub' => '238',
	'nmteam' => 'Centrals DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '123',
	'idclub' => '59',
	'nmteam' => 'HCAW Bussum DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '124',
	'idclub' => '150',
	'nmteam' => 'Zwijndrecht DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '125',
	'idclub' => '131',
	'nmteam' => 'Twins DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '126',
	'idclub' => '162',
	'nmteam' => 'Almere \'90 DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '127',
	'idclub' => '41',
	'nmteam' => 'Euro Stars DS1',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'F',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '128',
	'idclub' => '55',
	'nmteam' => 'Haarlem Nicols',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '129',
	'idclub' => '59',
	'nmteam' => 'Clickets HCAW',
	'cdsport' => 'HB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '130',
	'idclub' => '59',
	'nmteam' => 'Clickets HCAW',
	'cdsport' => 'SB',
	'cdclass' => 'SEN',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],
[
	'idteam' => '131',
	'nmteam' => 'TAS Detach Pirates',
	'cdsport' => 'HB',
	'cdgender' => 'M',
	'created_at' => '2019-03-24 09:23:27',
	'updated_by' => 'info@honkbalmuseum.nl',
],

    	];

        $table = $this->table('teams');
        $table->insert($data)
              ->save();

    }
}
