/* create a user that can only read */

SELECT SUBSTRING_INDEX(USER(), '@', -1) AS server;

IF server = 'localhost'
  DROP USER IF EXISTS 'reader'@'localhost' ;
  CREATE USER 'reader'@'localhost' IDENTIFIED BY 'O&wg94nl^G8t';
  GRANT SELECT ON *.* TO 'reader'@'localhost' IDENTIFIED BY 'O&wg94nl^G8t';
ENDIF  

SET @username = SELECT SUBSTRING_INDEX(USER(), '@', 1);

IF $servername = "localhost" THEN  
  DROP USER IF EXISTS 'reader'@'localhost' ;
  CREATE USER 'reader'@'localhost' IDENTIFIED BY 'O&wg94nl^G8t';
  GRANT SELECT ON *.* TO 'reader'@'localhost' IDENTIFIED BY 'O&wg94nl^G8t';
ELSE 
ENDIF 



SELECT J.JOB_ID,E.COMPANY_NAME,J.JOB_DESC,JT.JOBTYPE_NAME,J.COMPENSATION,ST.STATE_NAME,MC.METRO_CITY_NAME,I.INDUSTRY_NAME,
 J.JOB_CONTACT_PERSON,J.DT_INSRT,J.JOB_TITLE,J.JOB_EXP_DATE,J.SKILLS
 FROM JOBS J 
 JOIN EMPLOYER E ON J.COMPANY_ID=E.COMPANY_ID 
 JOIN LOOKUP_JOBTYPE JT ON J.JOB_TYPE=JT.JOBTYPE_ID
 JOIN LOOKUP_STATE ST ON J.STATE_ID=ST.STATE_ID
 JOIN JOBS_LOCATION JL ON J.JOB_ID=JL.JOB_ID
 JOIN LOOKUP_METRO_CITY MC ON JL.METRO_CITY_ID=MC.METRO_CITY_ID
 JOIN LOOKUP_INDUSTRY I ON J.INDUSTRY_ID=I.INDUSTRY_ID 
 JOIN JOBS_QUALIFICATION JQ ON J.JOB_ID=JQ.JOB_ID 
 JOIN LOOKUP_DEGREE_QUALIFICATION LDQ ON LDQ.QUALIFICATION_ID = JQ.QUALIFICATION_ID
 WHERE  J.ACTIVE='Y' AND J.DT_INSRT > COALESCE(pEmailSntDt,DATE_SUB(SYSDATE(),INTERVAL 4 DAY))  
AND
IF(JQ.COURSE_ID=0) 
THEN
IF(JQ.DEGREE_ID=0)
THEN J.SKILLS LIKE CONCAT('%', pSkills,'%')
ELSE
JQ.DEGREE_ID=pDegreeId OR J.SKILLS LIKE CONCAT('%', pSkills,'%')
END IF
ELSE
JQ.COURSE_ID=pCourseId OR IF(JQ.DEGREE_ID=0)
                      THEN
                      J.SKILLS LIKE CONCAT('%', pSkills,'%')
                      ELSE
                      JQ.DEGREE_ID=pDegreeId OR J.SKILLS LIKE CONCAT('%', pSkills,'%')
                      END IF
END IF                           
GROUP BY J.JOB_ID ORDER BY J.DT_INSRT DESC;



  DROP USER IF EXISTS 'reader'@'localhost' ;
  CREATE USER 'reader'@'localhost' IDENTIFIED BY 'BlHgGMd0';